In [1]:
import requests
import pandas as pd

In [2]:
from main import run_blast, extract_prefix_organism_pairs, filter_valid_wgs_ids, wait_for_blast_results

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
rows = 10000
taxons = ['Gregarinasina', 'Insecta', 'Crustacea', 'Annelida', 'Nematoda', 'Trematoda', 'Cestoda', 'jawless', 'fish']
prefixes = []
for taxon in taxons:
    print(taxon)
    response = requests.post('https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?', data={'q': f'&wt=xml&rows={rows}&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'}) 
    indexes = extract_prefix_organism_pairs(response.text)
    print(len(indexes), indexes)
    prefixes.append(extract_prefix_organism_pairs(response.text))

Gregarinasina
[WGS index] Found 7 matching entries.
7 [('AFNH01', 'Gregarina niphandrodes'), ('ABJQ01', 'Ascogregarina taiwanensis'), ('AFNH02', 'Gregarina niphandrodes'), ('JAHYSE01', 'Porospora cf. gigantea A'), ('JAQIFP01', 'Ophryocystis elektroscirrha'), ('JAHYSF01', 'Porospora cf. gigantea B'), ('JBLWGC01', 'Leidyana gryllorum')]
[WGS index] Found 7 matching entries.
Insecta
[WGS index] Found 7867 matching entries.

In [49]:
# Malacostraca -- канонические + мечниковилиды

rows = 10000
taxons = ['Malacostraca', 'Limnephilidae', 'Trichoptera']
prefixes = []
for taxon in taxons:
    print(taxon)
    response = requests.post('https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?', data={'q': f'&wt=xml&rows={rows}&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'}) 
    indexes = extract_prefix_organism_pairs(response.text)
    print(len(indexes), indexes)
    prefixes.append(extract_prefix_organism_pairs(response.text))

Malacostraca
[WGS index] Found 143 matching entries.
143 [('JAACYD01', 'Idotea baltica'), ('JANFXF01', 'Macrobrachium rosenbergii'), ('JQDR01', 'Hyalella azteca'), ('JQDR02', 'Hyalella azteca'), ('LQNS01', 'Parhyale hawaiensis'), ('JAVRFU01', 'Coenobita brevimanus'), ('CAUOHM01', 'Astacus astacus'), ('CAUOQP01', 'Astacus astacus'), ('LQIF01', 'Eriocheir sinensis'), ('FJVI01', 'Gammarus pulex'), ('CAUOHC01', 'Astacus astacus'), ('CAUOHM02', 'Astacus astacus'), ('CAUOKU01', 'Astacus astacus'), ('CAUOQP02', 'Astacus astacus'), ('BDMR01', 'Caridina multidentata'), ('BDMT01', 'Ligia exotica'), ('VCRD01', 'Trinorchestia longiramus'), ('SKFP01', 'Pandalus platyceros'), ('SAUD01', 'Armadillidium vulgare'), ('JABTEM01', 'Paralithodes platypus'), ('QWLK01', 'Penaeus vannamei'), ('JABKCB01', 'Penaeus chinensis'), ('BOPN01', 'Penaeus japonicus'), ('LQNS02', 'Parhyale hawaiensis'), ('JACMIE01', 'Portunus trituberculatus'), ('JAGGDN01', 'Portunus trituberculatus'), ('JAGTTE01', 'Penaeus japonicus'), ('JAHFWG01', 'Callinectes sapidus'), ('VSRR01', 'Portunus trituberculatus'), ('LQIF02', 'Eriocheir sinensis'), ('JAOPJN01', 'Callinectes sapidus'), ('JACJUY01', 'Platorchestia sp. MABIK'), ('JAGKTI01', 'Birgus latro'), ('JAGKTK01', 'Paralithodes camtschaticus'), ('JQDR03', 'Hyalella azteca'), ('MRZY01', 'Procambarus virginalis'), ('NIUR01', 'Penaeus japonicus'), ('NIUS01', 'Penaeus monodon'), ('QCYY01', 'Penaeus vannamei'), ('QUOF01', 'Palaemon carinicauda'), ('VOMN01', 'Orchestia grillus'), ('VSFE01', 'Cherax quadricarinatus'), ('WNGS01', 'Procambarus virginalis'), ('JAAVMY01', 'Eriocheir sinensis'), ('LYUU01', 'Armadillidium vulgare'), ('JACDRO01', 'Eriocheir sinensis'), ('JABERT01', 'Penaeus monodon'), ('JABUQX01', 'Trachelipus rathkii'), ('VIGR01', 'Penaeus monodon'), ('SDVV01', 'Gammarus roeselii'), ('SEYY01', 'Armadillidium nasatum'), ('WNWK01', 'Cherax destructor'), ('JAHLQT01', 'Homarus americanus'), ('JAPQNM01', 'Metacarcinus magister'), ('JASJYW01', 'Morinoia aosen'), ('CAUDMG01', 'Homarus gammarus'), ('CAUOHL01', 'Astacus astacus'), ('JAPQEV01', 'Cherax quadricarinatus'), ('JAHNEI01', 'Eriocheir sinensis'), ('JAJNBS01', 'Notopais sp. c TS-2021'), ('JAJNBT01', 'Notopais sp. p TS-2021'), ('JAOXOF01', 'Pagurus longicarpus'), ('JARBFZ01', 'Oratosquilla oratoria'), ('JBFOCG01', 'Procambarus clarkii'), ('JALHKN01', 'Hyalella sp. 3TK10'), ('JBAKBP01', 'Lithodes maja'), ('JBAKBQ01', 'Lithodes maja'), ('JARFOF01', 'Pagurus beringanus'), ('JARFYG01', 'Pagurus granosimanus'), ('JARUHE01', 'Archaeomysis grebnitzkii'), ('JASNJQ01', 'Pagurus hirsutiusculus'), ('JBAGKJ01', 'Phronima sedentaria'), ('CAXKWB01', 'Meganyctiphanes norvegica'), ('JAVIII01', 'Pandalus borealis'), ('JBEBFQ01', 'Macrobrachium rosenbergii'), ('DAWKWD01', 'Penaeus vannamei'), ('JBETKW01', 'Macrobrachium rosenbergii'), ('JAGYIC01', 'Penaeus indicus'), ('JAXIVD01', 'Cancer borealis'), ('JAXIVE01', 'Cancer borealis'), ('CANNZV01', 'Caprella mutica'), ('JAWWMC01', 'Portunus pelagicus'), ('JAYKKS01', 'Scylla paramamosain'), ('JBFNAF01', 'Penaeus vannamei'), ('CAXOTP01', 'Asellus aquaticus'), ('CAXOTQ01', 'Asellus aquaticus'), ('JARKIK01', 'Cherax quadricarinatus'), ('JAVBXC01', 'Scyllarides nodifer'), ('CAXAKS01', 'Ceratothoa steindachneri'), ('CAXAKT01', 'Ceratothoa steindachneri'), ('JAZBNH01', 'Panulirus ornatus'), ('JAIWQB01', 'Procambarus clarkii'), ('JAAFYK01', 'Penaeus monodon'), ('JANIEY01', 'Penaeus vannamei'), ('JAWQET01', 'Eriocheir sinensis'), ('JAXCGZ01', 'Halocaridina rubra'), ('BAABUL01', 'Neocaridina denticulata'), ('JARAKH01', 'Scylla paramamosain'), ('JANJGK01', 'Macrobrachium rosenbergii'), ('JACBPZ01', 'Penaeus monodon'), ('JAUTXX01', 'Panulirus laevicauda'), ('JAUTYZ01', 'Panulirus interruptus'), ('JAUTZA01', 'Panulirus longipes'), ('JAUUDT01', 'Panulirus ornatus'), ('JAUUDW01', 'Panulirus guttatus'), ('JAUUDY01', 'Panulirus inflatus'), ('JAUUDZ01', 'Panulirus versicolor'), ('JAUUEC01', 'Panulirus marginatus'), ('JAUUED01', 'Panulirus pascuensis'), ('JAUUEE01', 'Panulirus cygnus'), ('JAUUEF01', 'Panulirus homarus'), ('JAUUEG01', 'Panulirus gracilis'), ('JAWQEG01', 'Petrolisthes cinctipes'), ('JAWZYT01', 'Petrolisthes manimaculis'), ('JAYMFT01', 'Panulirus argus'), ('JACEEZ01', 'Chionoecetes opilio'), ('JAGKTJ01', 'Panulirus ornatus'), ('JAGKSU01', 'Penaeus chinensis'), ('JAJOZX01', 'Bathynomus jamesi'), ('JAQGCT01', 'Haplophthalmus danicus'), ('JAQIXM01', 'Porcellio scaber'), ('JAQIYL01', 'Trichoniscus pusillus'), ('JAVRFV01', 'Paralithodes platypus'), ('JAVRFW01', 'Portunus trituberculatus'), ('JBCDWE01', 'Cancer borealis'), ('JBHZIK01', 'Panulirus homarus'), ('JAZBEV01', 'Palaemon carinicauda'), ('CAXYIV01', 'Tethysbaena scabra'), ('JAVRFU02', 'Coenobita brevimanus'), ('JAYWIU01', 'Oratosquilla oratoria'), ('JBIMEQ01', 'Macrobrachium hainanense'), ('JBHUPZ01', 'Portunus trituberculatus'), ('CAZXJL01', 'Anilocra frontalis'), ('CAZYKG01', 'Anilocra frontalis'), ('CBDDMG01', 'Portunus segnis'), ('JBKSJC01', 'Potiberaba porakuara'), ('JBGOSA01', 'Macrobrachium rosenbergii'), ('CBCUCX01', 'Eriphia verrucosa'), ('JBBVRH01', 'Procambarus clarkii'), ('CBDBQM01', 'Jaera praehirsuta'), ('CBDBQN01', 'Jaera praehirsuta'), ('CBDAEV01', 'Jaera ischiosetosa'), ('CBDAEW01', 'Jaera ischiosetosa')]
[WGS index] Found 143 matching entries.
Limnephilidae
[WGS index] Found 22 matching entries.
22 [('JDSM01', 'Limnephilus lunatus'), ('CAKJTE01', 'Limnephilus lunatus'), ('CAKJTF01', 'Limnephilus lunatus'), ('CAKJUW01', 'Limnephilus marmoratus'), ('CAKMYE01', 'Limnephilus rhombicus'), ('JAHDVE01', 'Halesus radiatus'), ('JADDOG01', 'Hesperophylax magnus'), ('JAIUSX01', 'Hesperophylax magnus'), ('CAKMYE02', 'Limnephilus rhombicus'), ('JDSM02', 'Limnephilus lunatus'), ('CATOTV01', 'Limnephilus auricula'), ('CATOTW01', 'Limnephilus auricula'), ('CAKZFC01', 'Glyphotaelius pellucidus'), ('CAKZFD01', 'Glyphotaelius pellucidus'), ('CAKJTE02', 'Limnephilus lunatus'), ('CAKJTF02', 'Limnephilus lunatus'), ('CAKJUW02', 'Limnephilus marmoratus'), ('CAKMYO01', 'Limnephilus rhombicus'), ('CAKJUN01', 'Limnephilus marmoratus'), ('JAGUCF01', 'Micropterna sequax'), ('JAGWCC01', 'Drusus annulatus'), ('JAHDVE02', 'Halesus radiatus')]
[WGS index] Found 22 matching entries.
Trichoptera
[WGS index] Found 82 matching entries.
82 [('JDSM01', 'Limnephilus lunatus'), ('CAKJTE01', 'Limnephilus lunatus'), ('CAKJTF01', 'Limnephilus lunatus'), ('CAKJUW01', 'Limnephilus marmoratus'), ('CAKMYE01', 'Limnephilus rhombicus'), ('JAGVSO01', 'Rhyacophila evoluta'), ('JAHDVE01', 'Halesus radiatus'), ('JAHDVF01', 'Lepidostoma basale'), ('JAOXNN01', 'Hydropsyche betteni'), ('CAJYDF01', 'Sericostoma sp. HW-2014'), ('LZQS01', 'Streptomyces sp. IB2014 011-1'), ('QEIK01', 'Streptomyces sp. IB2014 011-12'), ('PZYU01', 'Glossosoma conforme'), ('JADDOG01', 'Hesperophylax magnus'), ('JADDOH01', 'Agrypnia vestita'), ('JAIUSX01', 'Hesperophylax magnus'), ('CANPUV01', 'Athripsodes cinereus'), ('CANPUW01', 'Athripsodes cinereus'), ('CAKMYE02', 'Limnephilus rhombicus'), ('JDSM02', 'Limnephilus lunatus'), ('NCQO01', 'Sericostoma sp. HW-2014'), ('JACZEN01', 'Cheumatopsyche charites'), ('VTFK01', 'Plectrocnemia conspersa'), ('WACJ01', 'Stenopsyche tienmushanensis'), ('JAHZML01', 'Eubasilissa splendida'), ('JAHZMQ01', 'Himalopsyche anomala'), ('CATOTV01', 'Limnephilus auricula'), ('CATOTW01', 'Limnephilus auricula'), ('JANIJI01', 'Leptonema lineaticorne'), ('JAPJYX01', 'Himalopsyche tibetana'), ('CAKZFC01', 'Glyphotaelius pellucidus'), ('CAKZFD01', 'Glyphotaelius pellucidus'), ('CATOGX01', 'Agapetus fuscipes'), ('CATOHA01', 'Agapetus fuscipes'), ('JAHFWH01', 'Himalopsyche tibetana'), ('JAHFWI01', 'Himalopsyche kuldschensis'), ('JAHFWJ01', 'Himalopsyche japonica'), ('JAPMAF01', 'Silvatares holzenthali'), ('JAPMAE01', 'Rhyacophila sp. 25_7'), ('JAPMAG01', 'Rhyacophila sp. Rhy_31_5'), ('CAUYVO01', 'Molanna angustata'), ('CAUYVX01', 'Molanna angustata'), ('CAUYWS01', 'Mystacides longicornis'), ('CAUYWX01', 'Ceraclea dissimilis'), ('CAUYXB01', 'Ceraclea dissimilis'), ('CAUYXC01', 'Mystacides longicornis'), ('CAXYGI01', 'Triaenodes bicolor'), ('CAXYGJ01', 'Triaenodes bicolor'), ('JARCGT01', 'Arctopsyche grandis'), ('CAKJTE02', 'Limnephilus lunatus'), ('CAKJTF02', 'Limnephilus lunatus'), ('CAKJUW02', 'Limnephilus marmoratus'), ('CAKMYO01', 'Limnephilus rhombicus'), ('JAILWY01', 'Atopsyche davidsoni'), ('JAGTXQ01', 'Odontocerum albicorne'), ('JAGVSL01', 'Himalopsyche phryganea'), ('JAGVSM01', 'Micrasema longulum'), ('JAGVSP01', 'Micrasema minimum'), ('JAGXCT01', 'Philopotamus ludificatus'), ('JAGYXB01', 'Rhyacophila brunnea'), ('CATKWI01', 'Odontocerum albicorne'), ('CATKWJ01', 'Odontocerum albicorne'), ('CAKJUN01', 'Limnephilus marmoratus'), ('JAGTTH01', 'Agraylea sexmaculata'), ('JAGTXP01', 'Agapetus fuscipes'), ('JAGTXR01', 'Glossosoma conforme'), ('JAGUCF01', 'Micropterna sequax'), ('JAGVSO02', 'Rhyacophila evoluta'), ('JAGXCS01', 'Micrasema longulum'), ('JAGVSN01', 'Parapsyche elsis'), ('JAGWCC01', 'Drusus annulatus'), ('JAHDVE02', 'Halesus radiatus'), ('JAHDVF02', 'Lepidostoma basale'), ('JAGVSQ01', 'Rhyacophila evoluta'), ('JAINEB01', 'Eubasilissa regina'), ('NZ_LZQS01', 'Streptomyces sp. IB2014 011-1'), ('NZ_QEIK01', 'Streptomyces sp. IB2014 011-12'), ('JAWQED01', 'Nectopsyche paramo'), ('JAOXNN02', 'Hydropsyche betteni'), ('VTON01', 'Hydropsyche tenuis'), ('JAUOEZ01', 'Limnocentropus insolitus'), ('JAURRE01', 'Phryganopsyche brunnea')]
[WGS index] Found 82 matching entries.

In [7]:
gregarina = prefixes[0]
insecta = prefixes[1]
crustacea = prefixes[2]
annelida = prefixes[3]
nematoda = prefixes[4]
trematoda = prefixes[5]
cestoda = prefixes[6]
jawless = prefixes[7]
fish = prefixes[8]

In [8]:
'gregarina', gregarina[:3], 'insecta', insecta[:3], 'crustacea', crustacea[:3], 'annelida', annelida[:3], 'nematoda', nematoda[:3], 'trematoda', trematoda[:3], 'cestoda', cestoda[:3], 'jawless', jawless, 'fish', fish[:3]

('gregarina',
 [('AFNH01', 'Gregarina niphandrodes'),
  ('ABJQ01', 'Ascogregarina taiwanensis'),
  ('JAHYSE01', 'Porospora cf. gigantea A')],
 'insecta',
 [('JARGDH01', 'Menopon gallinae'),
  ('AYNC02', 'Ephemera danica'),
  ('PVMI01', 'Aulacorthum solani')],
 'crustacea',
 [('JAACYD01', 'Idotea baltica'),
  ('JAINTR01', 'Capitulum mitella'),
  ('JANFXF01', 'Macrobrachium rosenbergii')],
 'annelida',
 [('CAIIXF01', 'Owenia fusiformis'),
  ('NZ_AMQM01', 'Helobdella robusta'),
  ('LQRL01', 'Hydroides elegans')],
 'nematoda',
 [('LTAM01', 'Ostertagia ostertagi'),
  ('LVRB01', 'Cooperia oncophora'),
  ('NZ_CAAC01', 'Caenorhabditis briggsae')],
 'trematoda',
 [('BADR01', 'Clonorchis sinensis'),
  ('AMPZ01', 'Schistosoma haematobium'),
  ('JXXN01', 'Fasciola hepatica')],
 'cestoda',
 [('APAU01', 'Echinococcus granulosus'),
  ('LWMJ01', 'Taenia asiatica'),
  ('LWMK01', 'Taenia saginata')],
 'jawless',
 [],
 'fish',
 [('JBCEYL01', 'Eleginops maclovinus'),
  ('AAKXES01', 'Salmonella enterica subsp. enterica serovar Enteritidis'),
  ('AAXOTF01', 'Vibrio parahaemolyticus')])

In [10]:
prefix_gregarina = [p for p, _ in gregarina]
prefix_gregarina = filter_valid_wgs_ids(prefix_gregarina)

prefix_insecta = [p for p, _ in insecta]
prefix_insecta = filter_valid_wgs_ids(prefix_insecta)

prefix_annelida = [p for p, _ in annelida]
prefix_annelida = filter_valid_wgs_ids(prefix_annelida)

prefix_nematoda = [p for p, _ in nematoda]
prefix_nematoda = filter_valid_wgs_ids(prefix_nematoda)

prefix_trematoda = [p for p, _ in trematoda]
prefix_trematoda = filter_valid_wgs_ids(prefix_trematoda)

prefix_cestoda = [p for p, _ in cestoda]
prefix_cestoda = filter_valid_wgs_ids(prefix_cestoda)

prefix_fish = [p for p, _ in fish]
prefix_fish = filter_valid_wgs_ids(prefix_fish)

INFO:main:Filtering batch 1: 7 prefixes
INFO:main:Total validated prefixes: 6
INFO:main:Filtering batch 1: 50 prefixes
INFO:main:Filtering batch 2: 50 prefixes
INFO:main:Filtering batch 3: 50 prefixes
INFO:main:Filtering batch 4: 50 prefixes
INFO:main:Filtering batch 5: 50 prefixes
INFO:main:Filtering batch 6: 50 prefixes
INFO:main:Filtering batch 7: 50 prefixes
INFO:main:Filtering batch 8: 50 prefixes
INFO:main:Filtering batch 9: 50 prefixes
INFO:main:Filtering batch 10: 50 prefixes
INFO:main:Filtering batch 11: 50 prefixes
INFO:main:Filtering batch 12: 50 prefixes
INFO:main:Filtering batch 13: 50 prefixes
INFO:main:Filtering batch 14: 50 prefixes
INFO:main:Filtering batch 15: 50 prefixes
INFO:main:Filtering batch 16: 50 prefixes
INFO:main:Filtering batch 17: 50 prefixes
INFO:main:Filtering batch 18: 50 prefixes
INFO:main:Filtering batch 19: 50 prefixes
INFO:main:Filtering batch 20: 50 prefixes
INFO:main:Filtering batch 21: 50 prefixes
INFO:main:Filtering batch 22: 50 prefixes
INFO:main:Filtering batch 23: 50 prefixes
INFO:main:Filtering batch 24: 50 prefixes
INFO:main:Filtering batch 25: 50 prefixes
INFO:main:Filtering batch 26: 50 prefixes
INFO:main:Filtering batch 27: 50 prefixes
INFO:main:Filtering batch 28: 50 prefixes
INFO:main:Filtering batch 29: 50 prefixes
INFO:main:Filtering batch 30: 50 prefixes
INFO:main:Filtering batch 31: 50 prefixes
INFO:main:Filtering batch 32: 50 prefixes
INFO:main:Filtering batch 33: 50 prefixes
INFO:main:Filtering batch 34: 50 prefixes
INFO:main:Filtering batch 35: 50 prefixes
INFO:main:Filtering batch 36: 50 prefixes
INFO:main:Filtering batch 37: 50 prefixes
INFO:main:Filtering batch 38: 50 prefixes
INFO:main:Filtering batch 39: 50 prefixes
INFO:main:Filtering batch 40: 50 prefixes
INFO:main:Filtering batch 41: 50 prefixes
INFO:main:Filtering batch 42: 50 prefixes
INFO:main:Filtering batch 43: 50 prefixes
INFO:main:Filtering batch 44: 50 prefixes
INFO:main:Filtering batch 45: 50 prefixes
INFO:main:Filtering batch 46: 50 prefixes
INFO:main:Filtering batch 47: 50 prefixes
INFO:main:Filtering batch 48: 50 prefixes
INFO:main:Filtering batch 49: 50 prefixes
INFO:main:Filtering batch 50: 50 prefixes
INFO:main:Filtering batch 51: 50 prefixes
INFO:main:Filtering batch 52: 50 prefixes
INFO:main:Filtering batch 53: 50 prefixes
INFO:main:Filtering batch 54: 50 prefixes
INFO:main:Filtering batch 55: 50 prefixes
INFO:main:Filtering batch 56: 50 prefixes
INFO:main:Filtering batch 57: 50 prefixes
INFO:main:Filtering batch 58: 50 prefixes
INFO:main:Filtering batch 59: 50 prefixes
INFO:main:Filtering batch 60: 50 prefixes
INFO:main:Filtering batch 61: 50 prefixes
INFO:main:Filtering batch 62: 50 prefixes
INFO:main:Filtering batch 63: 50 prefixes
INFO:main:Filtering batch 64: 50 prefixes
INFO:main:Filtering batch 65: 50 prefixes
INFO:main:Filtering batch 66: 50 prefixes
INFO:main:Filtering batch 67: 50 prefixes
INFO:main:Filtering batch 68: 50 prefixes
INFO:main:Filtering batch 69: 50 prefixes
INFO:main:Filtering batch 70: 50 prefixes
INFO:main:Filtering batch 71: 50 prefixes
INFO:main:Filtering batch 72: 50 prefixes
INFO:main:Filtering batch 73: 50 prefixes
INFO:main:Filtering batch 74: 50 prefixes
INFO:main:Filtering batch 75: 50 prefixes
INFO:main:Filtering batch 76: 50 prefixes
INFO:main:Filtering batch 77: 50 prefixes
INFO:main:Filtering batch 78: 50 prefixes
INFO:main:Filtering batch 79: 50 prefixes
INFO:main:Filtering batch 80: 50 prefixes
INFO:main:Filtering batch 81: 50 prefixes
INFO:main:Filtering batch 82: 50 prefixes
INFO:main:Filtering batch 83: 50 prefixes
INFO:main:Filtering batch 84: 50 prefixes
INFO:main:Filtering batch 85: 50 prefixes
INFO:main:Filtering batch 86: 50 prefixes
INFO:main:Filtering batch 87: 50 prefixes
INFO:main:Filtering batch 88: 50 prefixes
INFO:main:Filtering batch 89: 50 prefixes
INFO:main:Filtering batch 90: 50 prefixes
INFO:main:Filtering batch 91: 50 prefixes
INFO:main:Filtering batch 92: 50 prefixes
INFO:main:Filtering batch 93: 50 prefixes
INFO:main:Filtering batch 94: 50 prefixes
INFO:main:Filtering batch 95: 50 prefixes
INFO:main:Filtering batch 96: 50 prefixes
INFO:main:Filtering batch 97: 50 prefixes
INFO:main:Filtering batch 98: 50 prefixes
INFO:main:Filtering batch 99: 50 prefixes
INFO:main:Filtering batch 100: 50 prefixes
INFO:main:Filtering batch 101: 50 prefixes
INFO:main:Filtering batch 102: 50 prefixes
INFO:main:Filtering batch 103: 50 prefixes
INFO:main:Filtering batch 104: 50 prefixes
INFO:main:Filtering batch 105: 50 prefixes
INFO:main:Filtering batch 106: 50 prefixes
INFO:main:Filtering batch 107: 50 prefixes
INFO:main:Filtering batch 108: 50 prefixes
INFO:main:Filtering batch 109: 50 prefixes
INFO:main:Filtering batch 110: 50 prefixes
INFO:main:Filtering batch 111: 50 prefixes
INFO:main:Filtering batch 112: 50 prefixes
INFO:main:Filtering batch 113: 50 prefixes
INFO:main:Filtering batch 114: 50 prefixes
INFO:main:Filtering batch 115: 50 prefixes
INFO:main:Filtering batch 116: 50 prefixes
INFO:main:Filtering batch 117: 50 prefixes
INFO:main:Filtering batch 118: 50 prefixes
INFO:main:Filtering batch 119: 50 prefixes
INFO:main:Filtering batch 120: 50 prefixes
INFO:main:Filtering batch 121: 50 prefixes
INFO:main:Filtering batch 122: 50 prefixes
INFO:main:Filtering batch 123: 50 prefixes
INFO:main:Filtering batch 124: 50 prefixes
INFO:main:Filtering batch 125: 50 prefixes
INFO:main:Filtering batch 126: 50 prefixes
INFO:main:Filtering batch 127: 50 prefixes
INFO:main:Filtering batch 128: 50 prefixes
INFO:main:Filtering batch 129: 50 prefixes
INFO:main:Filtering batch 130: 50 prefixes
INFO:main:Filtering batch 131: 50 prefixes
INFO:main:Filtering batch 132: 50 prefixes
INFO:main:Filtering batch 133: 50 prefixes
INFO:main:Filtering batch 134: 50 prefixes
INFO:main:Filtering batch 135: 50 prefixes
INFO:main:Filtering batch 136: 50 prefixes
INFO:main:Filtering batch 137: 50 prefixes
INFO:main:Filtering batch 138: 50 prefixes
INFO:main:Filtering batch 139: 50 prefixes
INFO:main:Filtering batch 140: 50 prefixes
INFO:main:Filtering batch 141: 50 prefixes
INFO:main:Filtering batch 142: 50 prefixes
INFO:main:Filtering batch 143: 50 prefixes
INFO:main:Filtering batch 144: 50 prefixes
INFO:main:Filtering batch 145: 50 prefixes
INFO:main:Filtering batch 146: 50 prefixes
INFO:main:Filtering batch 147: 50 prefixes
INFO:main:Filtering batch 148: 50 prefixes
INFO:main:Filtering batch 149: 47 prefixes
INFO:main:Total validated prefixes: 6896
INFO:main:Filtering batch 1: 50 prefixes
INFO:main:Filtering batch 2: 50 prefixes
INFO:main:Filtering batch 3: 45 prefixes
INFO:main:Total validated prefixes: 142
INFO:main:Filtering batch 1: 50 prefixes
INFO:main:Filtering batch 2: 50 prefixes
INFO:main:Filtering batch 3: 50 prefixes
INFO:main:Filtering batch 4: 50 prefixes
INFO:main:Filtering batch 5: 50 prefixes
INFO:main:Filtering batch 6: 50 prefixes
INFO:main:Filtering batch 7: 50 prefixes
INFO:main:Filtering batch 8: 50 prefixes
INFO:main:Filtering batch 9: 50 prefixes
INFO:main:Filtering batch 10: 50 prefixes
INFO:main:Filtering batch 11: 50 prefixes
INFO:main:Filtering batch 12: 50 prefixes
INFO:main:Filtering batch 13: 50 prefixes
INFO:main:Filtering batch 14: 7 prefixes
INFO:main:Total validated prefixes: 600
INFO:main:Filtering batch 1: 50 prefixes
INFO:main:Filtering batch 2: 49 prefixes
INFO:main:Total validated prefixes: 63
INFO:main:Filtering batch 1: 44 prefixes
INFO:main:Total validated prefixes: 33
INFO:main:Filtering batch 1: 50 prefixes
INFO:main:Filtering batch 2: 50 prefixes
INFO:main:Filtering batch 3: 50 prefixes
INFO:main:Filtering batch 4: 50 prefixes
INFO:main:Filtering batch 5: 50 prefixes
INFO:main:Filtering batch 6: 50 prefixes
INFO:main:Filtering batch 7: 50 prefixes
INFO:main:Filtering batch 8: 50 prefixes
INFO:main:Filtering batch 9: 50 prefixes
INFO:main:Filtering batch 10: 50 prefixes
INFO:main:Filtering batch 11: 50 prefixes
INFO:main:Filtering batch 12: 50 prefixes
INFO:main:Filtering batch 13: 50 prefixes
INFO:main:Filtering batch 14: 50 prefixes
INFO:main:Filtering batch 15: 50 prefixes
INFO:main:Filtering batch 16: 50 prefixes
INFO:main:Filtering batch 17: 50 prefixes
INFO:main:Filtering batch 18: 50 prefixes
INFO:main:Filtering batch 19: 50 prefixes
INFO:main:Filtering batch 20: 50 prefixes
INFO:main:Filtering batch 21: 50 prefixes
INFO:main:Filtering batch 22: 50 prefixes
INFO:main:Filtering batch 23: 50 prefixes
INFO:main:Filtering batch 24: 50 prefixes
INFO:main:Filtering batch 25: 50 prefixes
INFO:main:Filtering batch 26: 50 prefixes
INFO:main:Filtering batch 27: 50 prefixes
INFO:main:Filtering batch 28: 50 prefixes
INFO:main:Filtering batch 29: 50 prefixes
INFO:main:Filtering batch 30: 50 prefixes
INFO:main:Filtering batch 31: 50 prefixes
INFO:main:Filtering batch 32: 50 prefixes
INFO:main:Filtering batch 33: 50 prefixes
INFO:main:Filtering batch 34: 50 prefixes
INFO:main:Filtering batch 35: 50 prefixes
INFO:main:Filtering batch 36: 50 prefixes
INFO:main:Filtering batch 37: 50 prefixes
INFO:main:Filtering batch 38: 50 prefixes
INFO:main:Filtering batch 39: 50 prefixes
INFO:main:Filtering batch 40: 50 prefixes
INFO:main:Filtering batch 41: 50 prefixes
INFO:main:Filtering batch 42: 50 prefixes
INFO:main:Filtering batch 43: 50 prefixes
INFO:main:Filtering batch 44: 50 prefixes
INFO:main:Filtering batch 45: 50 prefixes
INFO:main:Filtering batch 46: 50 prefixes
INFO:main:Filtering batch 47: 50 prefixes
INFO:main:Filtering batch 48: 50 prefixes
INFO:main:Filtering batch 49: 50 prefixes
INFO:main:Filtering batch 50: 50 prefixes
INFO:main:Filtering batch 51: 50 prefixes
INFO:main:Filtering batch 52: 50 prefixes
INFO:main:Filtering batch 53: 50 prefixes
INFO:main:Filtering batch 54: 50 prefixes
INFO:main:Filtering batch 55: 50 prefixes
INFO:main:Filtering batch 56: 50 prefixes
INFO:main:Filtering batch 57: 50 prefixes
INFO:main:Filtering batch 58: 50 prefixes
INFO:main:Filtering batch 59: 50 prefixes
INFO:main:Filtering batch 60: 50 prefixes
INFO:main:Filtering batch 61: 50 prefixes
INFO:main:Filtering batch 62: 50 prefixes
INFO:main:Filtering batch 63: 50 prefixes
INFO:main:Filtering batch 64: 50 prefixes
INFO:main:Filtering batch 65: 50 prefixes
INFO:main:Filtering batch 66: 50 prefixes
INFO:main:Filtering batch 67: 50 prefixes
INFO:main:Filtering batch 68: 50 prefixes
INFO:main:Filtering batch 69: 50 prefixes
INFO:main:Filtering batch 70: 50 prefixes
INFO:main:Filtering batch 71: 50 prefixes
INFO:main:Filtering batch 72: 50 prefixes
INFO:main:Filtering batch 73: 50 prefixes
INFO:main:Filtering batch 74: 50 prefixes
INFO:main:Filtering batch 75: 50 prefixes
INFO:main:Filtering batch 76: 50 prefixes
INFO:main:Filtering batch 77: 50 prefixes
INFO:main:Filtering batch 78: 50 prefixes
INFO:main:Filtering batch 79: 50 prefixes
INFO:main:Filtering batch 80: 50 prefixes
INFO:main:Filtering batch 81: 50 prefixes
INFO:main:Filtering batch 82: 50 prefixes
INFO:main:Filtering batch 83: 50 prefixes
INFO:main:Filtering batch 84: 50 prefixes
INFO:main:Filtering batch 85: 50 prefixes
INFO:main:Filtering batch 86: 50 prefixes
INFO:main:Filtering batch 87: 50 prefixes
INFO:main:Filtering batch 88: 50 prefixes
INFO:main:Filtering batch 89: 50 prefixes
INFO:main:Filtering batch 90: 50 prefixes
INFO:main:Filtering batch 91: 50 prefixes
INFO:main:Filtering batch 92: 50 prefixes
INFO:main:Filtering batch 93: 50 prefixes
INFO:main:Filtering batch 94: 50 prefixes
INFO:main:Filtering batch 95: 50 prefixes
INFO:main:Filtering batch 96: 50 prefixes
INFO:main:Filtering batch 97: 50 prefixes
INFO:main:Filtering batch 98: 50 prefixes
INFO:main:Filtering batch 99: 50 prefixes
INFO:main:Filtering batch 100: 50 prefixes
INFO:main:Filtering batch 101: 50 prefixes
INFO:main:Filtering batch 102: 50 prefixes
INFO:main:Filtering batch 103: 50 prefixes
INFO:main:Filtering batch 104: 50 prefixes
INFO:main:Filtering batch 105: 50 prefixes
INFO:main:Filtering batch 106: 50 prefixes
INFO:main:Filtering batch 107: 50 prefixes
INFO:main:Filtering batch 108: 50 prefixes
INFO:main:Filtering batch 109: 50 prefixes
INFO:main:Filtering batch 110: 50 prefixes
INFO:main:Filtering batch 111: 50 prefixes
INFO:main:Filtering batch 112: 50 prefixes
INFO:main:Filtering batch 113: 50 prefixes
INFO:main:Filtering batch 114: 50 prefixes
INFO:main:Filtering batch 115: 50 prefixes
INFO:main:Filtering batch 116: 50 prefixes
INFO:main:Filtering batch 117: 50 prefixes
INFO:main:Filtering batch 118: 50 prefixes
INFO:main:Filtering batch 119: 50 prefixes
INFO:main:Filtering batch 120: 50 prefixes
INFO:main:Filtering batch 121: 46 prefixes
INFO:main:Total validated prefixes: 4259

In [16]:
prefix_gregarina, prefix_insecta, prefix_annelida, prefix_nematoda, prefix_trematoda, prefix_cestoda, prefix_fish

({'ABJQ01': 'Ascogregarina taiwanensis',
  'AFNH02': 'Gregarina niphandrodes',
  'JAHYSE01': 'Porospora cf. gigantea A',
  'JAHYSF01': 'Porospora cf. gigantea B',
  'JAQIFP01': 'Ophryocystis elektroscirrha',
  'JBLWGC01': 'Leidyana gryllorum'},
 {'AYNC02': 'Ephemera danica',
  'JARGDH01': 'Menopon gallinae',
  'JAVLTQ01': 'Hepialus xiaojinensis',
  'PVMI01': 'Aulacorthum solani',
  'CAZDIM01': 'Pammene suspectana',
  'AADE02': 'Drosophila pseudoobscura pseudoobscura',
  'FBXZ01': 'Spodoptera frugiperda',
  'FJUZ01': 'Spodoptera frugiperda',
  'JYND01': 'Drosophila athabasca',
  'LMAV01': 'Aedes albopictus',
  'NHMN01': 'Helicoverpa armigera',
  'NQII01': 'Clitarchus hookeri',
  'NTHM01': 'Galleria mellonella',
  'PDEX02': 'Melanaphis sacchari',
  'QANI01': 'Camponotus floridanus',
  'QBDW01': 'Maconellicoccus hirsutus',
  'QEWZ01': 'Schizaphis graminum',
  'QGMW01': 'Sipha flava',
  'QKMV01': 'Lednia tumana',
  'AAJJ02': 'Tribolium castaneum',
  'AOFN02': 'Athalia rosae',
  'AOSB01': 'Nilaparvata lugens',
  'AUST01': 'Zootermopsis nevadensis',
  'CEMD01': 'Nasutitermes exitiosus',
  'CEME01': 'Nasutitermes exitiosus',
  'CEMF01': 'Nasutitermes exitiosus',
  'CVRI01': 'Clunio marinus',
  'FAPG01': 'Heliconius hecale felix',
  'FIZR01': 'Ferrisia virgata',
  'FIZS01': 'Maconellicoccus hirsutus',
  'FIZT01': 'Paracoccus marginatus',
  'FIZU01': 'Pseudococcus longispinus',
  'FIZV01': 'Trionymus perrisii',
  'FKYK01': 'Trabutina mannipara',
  'FWDL01': 'Chironomus riparius',
  'JMCM01': 'Dactylopius coccus',
  'JPHR01': 'Dinoponera quadriceps',
  'JRES01': 'Lucilia cuprina',
  'JTEQ01': 'Piezodorus guildinii',
  'LYTB01': 'Drosophila biarmipes',
  'LYTC01': 'Drosophila nasuta',
  'LYTD01': 'Drosophila bipectinata',
  'LYTE01': 'Drosophila takahashii',
  'MOOZ01': 'Achalarus lyciades',
  'NBZA01': 'Aleochara bilineata',
  'NCVS01': 'Goniozus legneri',
  'NDWT01': 'Drosophila melanogaster',
  'NFMG01': 'Helicoverpa zea',
  'NHTH01': 'Galleria mellonella',
  'NIFY01': 'Drosophila simulans',
  'NIGA01': 'Drosophila mauritiana',
  'NIGP01': 'Aedes aegypti',
  'NJDC01': 'Calephelis virginiensis',
  'NJRK01': 'Aphaenogaster rudis',
  'NJRL01': 'Aphaenogaster rudis',
  'NJRM01': 'Aphaenogaster picea',
  'NJRN01': 'Aphaenogaster miamiana',
  'NJRO01': 'Aphaenogaster fulva',
  'NJRP01': 'Aphaenogaster floridana',
  'NJRQ01': 'Aphaenogaster ashmeadi',
  'OFSG01': 'Xenocatantops brachycerus',
  'PEHJ01': 'Vanessa tameamea',
  'PGFK01': 'Timema cristinae',
  'PGFW01': 'Haematobia irritans',
  'PGTA01': 'Timema cristinae',
  'QFTL02': 'Cydia pomonella',
  'SMLS01': 'Popillia japonica',
  'SNMR01': 'Tuta absoluta',
  'SSSI01': 'Oryzaephilus surinamensis',
  'ASCI01': 'Bombyx huttoni',
  'AVCP01': 'Locusta migratoria',
  'BLKR01': 'Teleogryllus occipitalis',
  'CADCXU01': 'Nesidiocoris tenuis',
  'FAPN01': 'Heliconius cydno alithea',
  'FAPT01': 'Heliconius cydno weymeri',
  'FAPV01': 'Heliconius cydno cydnides',
  'FAPX01': 'Heliconius cydno alithea',
  'FAPY01': 'Heliconius heurippa',
  'FAQA01': 'Heliconius elevatus',
  'FAQB01': 'Heliconius cydno cordula',
  'FAQC01': 'Heliconius cydno chioneus',
  'FAQE01': 'Heliconius cydno chioneus',
  'FAQF01': 'Heliconius hecale',
  'FAQG01': 'Heliconius heurippa',
  'FAQJ01': 'Heliconius cydno zelinde',
  'FAQK01': 'Heliconius cydno alithea',
  'FAQO01': 'Heliconius elevatus',
  'JAADKU01': 'Solenopsis invicta',
  'JAAGEC01': 'Odontomachus brunneus',
  'JXOT01': 'Calliphora vicina',
  'JXPE01': 'Holcocephala fusca',
  'JXPG01': 'Megaselia abdita',
  'JXPL01': 'Sphyracephala brevicornis',
  'JXPN01': 'Tephritis californica',
  'JXPP01': 'Tipula oleracea',
  'LADI01': 'Papilio xuthus',
  'LADJ01': 'Papilio machaon',
  'LBMM01': 'Lasius niger',
  'LCWJ01': 'Anopheles gambiae',
  'LGAG01': 'Lerema accius',
  'LJCH01': 'Nicrophorus vespilloides',
  'LJIG01': 'Oryctes borbonicus',
  'LKEW01': 'Atta colombica',
  'LKEX01': 'Cyphomyrmex costatus',
  'LKEZ01': 'Trachymyrmex septentrionalis',
  'LKFA01': 'Trachymyrmex zeteki',
  'LQNK01': 'Phoebis sennae',
  'LRFB01': 'Cimex hemipterus',
  'LWKS01': 'Zaprionus indianus',
  'LWME01': 'Pieris rapae',
  'LXJY01': 'Myzus persicae',
  'MAMS01': 'Bemisia tabaci',
  'MNAF02': 'Aedes albopictus',
  'MNCL01': 'Proctacanthus coquilletti',
  'MWIU01': 'Drosophila melanogaster',
  'QUOG01': 'Polistes dorsalis',
  'QUOH01': 'Polistes metricus',
  'QUOI01': 'Polistes fuscatus',
  'VNHH02': 'Drosophila virilis',
  'DULD01': 'Drosophila busckii',
  'FAQP01': 'Heliconius elevatus',
  'FAQS01': 'Heliconius cydno chioneus',
  'FAQT01': 'Heliconius cydno chioneus',
  'FAQU01': 'Heliconius melpomene aglaope',
  'FAQV01': 'Heliconius elevatus',
  'FAQY01': 'Heliconius melpomene amaryllis',
  'FARA01': 'Heliconius melpomene aglaope',
  'FARB01': 'Heliconius melpomene aglaope',
  'FARC01': 'Heliconius melpomene amaryllis',
  'FARG01': 'Heliconius melpomene amaryllis',
  'FARK01': 'Heliconius melpomene bellula',
  'FARR01': 'Heliconius melpomene melpomene',
  'FARW01': 'Heliconius melpomene melpomene',
  'FARY01': 'Heliconius melpomene melpomene',
  'FARZ01': 'Heliconius melpomene meriana',
  'FASA01': 'Heliconius melpomene melpomene',
  'FASE01': 'Heliconius melpomene rosina',
  'FASF01': 'Heliconius melpomene rosina',
  'FASG01': 'Heliconius melpomene rosina',
  'FASJ01': 'Heliconius melpomene rosina',
  'FAST01': 'Heliconius pachinus',
  'FASY01': 'Heliconius pardalinus ssp. n. KMK-2015',
  'FATA01': 'Heliconius pardalinus ssp. n. KMK-2015',
  'FATG01': 'Heliconius pardalinus ssp. n. KMK-2015',
  'FATH01': 'Heliconius timareta timareta',
  'FATT01': 'Heliconius timareta',
  'FATV01': 'Heliconius timareta',
  'FATY01': 'Heliconius timareta',
  'FATZ01': 'Heliconius hecale',
  'FAUC01': 'Heliconius hecale',
  'FAUF01': 'Heliconius cydno cydnides',
  'FAUG01': 'Heliconius hecale',
  'JAAEAF01': 'Triatoma infestans',
  'JXPU01': 'Aedes aegypti',
  'JXPX01': 'Sarcophagidae sp. BV-2014',
  'JXUM01': 'Aedes albopictus',
  'LGAM02': 'Bactrocera oleae',
  'LULA01': 'Anopheles maculatus',
  'LULB01': 'Anopheles cracens',
  'LVVV01': 'Amphinemura sulcicollis',
  'LVVW01': 'Isoperla grammatica',
  'LVVX01': 'Baetis rhodani',
  'MKQC01': 'Spodoptera frugiperda',
  'MPKX01': 'Diuraphis noxia',
  'NKXL01': 'Dryococelus australis',
  'VMOF01': 'Trialeurodes vaporariorum',
  'VTPC01': 'Ignelater luminosus',
  'WNNL01': 'Spodoptera exigua',
  'WOFM01': 'Ericerus pela',
  'AOHK02': 'Ceratitis capitata',
  'CADEPI01': 'Cloeon dipterum',
  'DUEA01': 'Danaus plexippus plexippus',
  'JAABVI01': 'Dendrolimus punctatus',
  'JAANDI01': 'Drosophila melanogaster',
  'JMPT03': 'Halyomorpha halys',
  'JXPI01': 'Neobellieria bullata',
  'LSRL02': 'Drosophila navojoa',
  'MRUE01': 'Drosophila neonasuta',
  'NPMM01': 'Formica exsecta',
  'PPHH01': 'Trichoplusia ni',
  'QMEN02': 'Scaptodrosophila lebanonensis',
  'QMEO02': 'Drosophila virilis',
  'QMEP02': 'Drosophila novamexicana',
  'QMEQ02': 'Drosophila hydei',
  'QMER02': 'Drosophila erecta',
  'SISJ02': 'Drosophila melanogaster',
  'SIXD01': 'Drosophila melanogaster',
  'SSSJ01': 'Solenopsis invicta',
  'SZUW01': 'Drosophila biarmipes',
  'VCKU01': 'Drosophila azteca',
  'VCKV01': 'Drosophila orena',
  'VFXL01': 'Phenacoccus solenopsis',
  'VJOP01': 'Trialeurodes vaporariorum',
  'VNJL01': 'Drosophila bakoue',
  'VNJM01': 'Drosophila kanapiae',
  'VNJN01': 'Drosophila mayri',
  'VNJO01': 'Drosophila tani',
  'VNJP01': 'Drosophila vulcana',
  'VNJQ01': 'Drosophila truncata',
  'VNJR01': 'Drosophila punjabiensis',
  'VNJS01': 'Drosophila watanabei',
  'VNJT01': 'Drosophila burlai',
  'VNJU01': 'Drosophila seguyi',
  'VNJV01': 'Drosophila nikananu',
  'VNJW01': 'Drosophila auraria',
  'VNJX01': 'Drosophila jambulina',
  'VNJY01': 'Drosophila bocki',
  'VNJZ01': 'Drosophila asahinai',
  'VNKA01': 'Drosophila birchii',
  'VNKB01': 'Drosophila leontia',
  'VNKC01': 'Drosophila pectinifera',
  'VNKD01': 'Drosophila serrata',
  'VNKE01': 'Drosophila bunnanda',
  'VNKF01': 'Drosophila lacteicornis',
  'VNKG01': 'Drosophila triauraria',
  'VNKH01': 'Drosophila rufa',
  'VYII01': 'Contarinia nasturtii',
  'WHVK01': 'Trichoplusia ni',
  'WIOZ01': 'Drosophila bifasciata',
  'ABLF02': 'Acyrthosiphon pisum',
  'AEAQ02': 'Solenopsis invicta',
  'JAAIXI01': 'Heliconius nattereri',
  'JAATLP01': 'Heliconius melpomene melpomene',
  'JABEOT01': 'Anopheles stephensi',
  'JABRWK01': 'Hypothenemus hampei',
  'JABVZV01': 'Lamprigera yunnana',
  'JABVZW01': 'Abscondita terminalis',
  'LIED01': 'Bemisia tabaci',
  'LWBZ01': 'Fusarium sp. FSSC_6',
  'LYUA01': 'Calopteryx splendens',
  'NGKO01': 'Drosophila subobscura',
  'NKQN01': 'Trichoplusia ni',
  'NWQH01': 'Drosophila hydei',
  'PGRJ01': 'Drosophila melanogaster',
  'PGRK01': 'Drosophila melanogaster',
  'PGRL01': 'Drosophila melanogaster',
  'PGRM01': 'Drosophila melanogaster',
  'PGRN01': 'Drosophila melanogaster',
  'PGRO01': 'Drosophila melanogaster',
  'PGRP01': 'Drosophila melanogaster',
  'PGRQ01': 'Drosophila melanogaster',
  'PGRR01': 'Drosophila melanogaster',
  'PGRS01': 'Drosophila melanogaster',
  'PGRT01': 'Drosophila melanogaster',
  'PGRU01': 'Drosophila melanogaster',
  'PGRV01': 'Drosophila melanogaster',
  'PGRW01': 'Drosophila melanogaster',
  'PZYU01': 'Glossosoma conforme',
  'QKMT02': 'Monomorium pharaonis',
  'QMET02': 'Drosophila persimilis',
  'QOIP01': 'Ooceraea biroi',
  'QORX02': 'Rhopalosiphum maidis',
  'QVAO01': 'Ctenocephalides felis',
  'QZCQ01': 'Hyposmocoma kahamanoa',
  'RCWQ01': 'Anopheles funestus',
  'RJWF01': 'Lymantria dispar dispar',
  'RSAL01': 'Chilo suppressalis',
  'RXPK01': 'Protaetia brevitarsis',
  'SCDR01': 'Drosophila nigromelanica',
  'SCDS01': 'Drosophila nigromelanica',
  'SCDU01': 'Drosophila melanica',
  'SCDW01': 'Drosophila robusta',
  'SCDY01': 'Drosophila micromelanica',
  'SCDZ01': 'Drosophila lacertosa',
  'SCEA01': 'Drosophila lacertosa',
  'SGAY01': 'Cataglyphis hispanica',
  'SJPC01': 'Cataglyphis niger',
  'WWNF01': 'Drosophila suzukii',
  'WWNG01': 'Drosophila suzukii',
  'CAJZBC01': 'Hydraecia micacea',
  'CAJZBE01': 'Hydraecia micacea',
  'CAJZBG01': 'Agrochola circellaris',
  'CAJZBH01': 'Coremacera marginata',
  'CAJZBI01': 'Agrochola circellaris',
  'CAJZBJ01': 'Eupsilia transversa',
  'CAJZBK01': 'Agriopis aurantiaria',
  'CAJZBM01': 'Ptilodon capucinus',
  'CAJZBP01': 'Eilema depressum',
  'CAJZBR01': 'Sesia apiformis',
  'CAJZBS01': 'Coremacera marginata',
  'CAJZBT01': 'Tenthredo notha',
  'CAJZBU01': 'Melanostoma mellinum',
  'CAJZBX01': 'Anoplius nigerrimus',
  'CAJZBY01': 'Thecocarcelia acutangulata',
  'CAJZBZ01': 'Sesia apiformis',
  'CAJZCA01': 'Thecocarcelia acutangulata',
  'CAJZHC01': 'Spilarctia lutea',
  'CAJZHO01': 'Spilarctia lutea',
  'JACGEL01': 'Elaeidobius kamerunicus',
  'JADFFN01': 'Anopheles stephensi',
  'JADFFO01': 'Anopheles merus',
  'JADFTP01': 'Anopheles coluzzii',
  'JADFTQ01': 'Anopheles arabiensis',
  'JADKZB01': 'Drosophila nasuta',
  'JADKZF01': 'Drosophila nasuta',
  'JADLKD01': 'Drosophila nasuta',
  'JADLOZ01': 'Ectropis grisescens',
  'JADWYY01': 'Laodelphax striatellus',
  'JADWYZ01': 'Sogatella furcifera',
  'JAEBDM01': 'Heliconius numata',
  'JAEBDN01': 'Heliconius numata',
  'JAEBDO01': 'Heliconius numata',
  'JAEBDR01': 'Heliconius numata',
  'JAEBDS01': 'Heliconius numata',
  'JAEBDT01': 'Heliconius numata',
  'JAEBDU01': 'Heliconius numata',
  'JAEBDV01': 'Heliconius numata',
  'JAEBDW01': 'Heliconius numata',
  'JAEBDX01': 'Heliconius numata',
  'JAEQBL01': 'Danaus plexippus',
  'JAEQMK01': 'Solenopsis invicta',
  'JAEUYN01': 'Euura lappo',
  'JAEVLZ01': 'Lymantria dispar',
  'JAFDUT01': 'Coelopa frigida',
  'JAGFPH01': 'Philaenus spumarius',
  'JASI01': 'Cerapachys biroi',
  'OUUW01': 'Drosophila guanche',
  'RKRM01': 'Scaptomyza flava',
  'WUTJ02': 'Spodoptera frugiperda',
  'CADEBA01': 'Bemisia tabaci',
  'CAJEWF01': 'Bemisia tabaci',
  'CAJEWG01': 'Bemisia tabaci',
  'CAJEWH01': 'Bemisia tabaci',
  'CAJEWI01': 'Bemisia tabaci',
  'CAJHWU02': 'Vanessa atalanta',
  'CAJHWX02': 'Vanessa atalanta',
  'CAJMZM01': 'Noctua pronuba',
  'CAJMZN01': 'Vanessa cardui',
  'CAJMZO01': 'Noctua pronuba',
  'CAJMZQ01': 'Xylota sylvarum',
  'CAJZCT01': 'Eilema sororculum',
  'CAJZCU01': 'Eilema sororculum',
  'CAJZCY01': 'Anopheles atroparvus',
  'CAJZKA01': 'Ancistrocerus nigricornis',
  'CAJZLQ01': 'Bellardia pandia',
  'JAEMMO01': 'Drosophila melanogaster',
  'JAEMMP01': 'Drosophila melanogaster',
  'JAEMMQ01': 'Drosophila melanogaster',
  'JAEMMR01': 'Drosophila melanogaster',
  'JAEMMS01': 'Drosophila melanogaster',
  'JAEMMT01': 'Drosophila melanogaster',
  'JAEMMU01': 'Drosophila melanogaster',
  'JAEMMV01': 'Drosophila melanogaster',
  'JAEMMW01': 'Drosophila melanogaster',
  'JAEMMX01': 'Drosophila melanogaster',
  'JAEMMY01': 'Drosophila melanogaster',
  'JAEMMZ01': 'Drosophila melanogaster',
  'JAEMNA01': 'Drosophila melanogaster',
  'JAEMNB01': 'Drosophila melanogaster',
  'JAEMNC01': 'Drosophila melanogaster',
  'JAEMND01': 'Drosophila melanogaster',
  'JAEMNE01': 'Drosophila melanogaster',
  'JAEMNF01': 'Drosophila melanogaster',
  'JAEMNG01': 'Drosophila melanogaster',
  'JAEMNH01': 'Drosophila melanogaster',
  'JAEMNI01': 'Drosophila melanogaster',
  'JAEMNJ01': 'Drosophila melanogaster',
  'JAEMNK01': 'Drosophila melanogaster',
  'JAEMNL01': 'Drosophila melanogaster',
  'JAEMNM01': 'Drosophila melanogaster',
  'JAEMNN01': 'Drosophila melanogaster',
  'JAEMNO01': 'Drosophila melanogaster',
  'JAEMNP01': 'Drosophila melanogaster',
  'JAEMNQ01': 'Drosophila melanogaster',
  'JAEMNR01': 'Drosophila melanogaster',
  'JAEMNS01': 'Drosophila melanogaster',
  'JAEMNT01': 'Drosophila melanogaster',
  'JAGTJF01': 'Aphis gossypii',
  'JAIRBL01': 'Scirpophaga incertulas',
  'AAAB01': 'Anopheles gambiae str. PEST',
  'AAEU02': 'Drosophila yakuba',
  'AAFS01': 'Drosophila pseudoobscura pseudoobscura',
  'AAGH01': 'Drosophila simulans',
  'AAPQ01': 'Drosophila erecta',
  'AAPT01': 'Drosophila grimshawi',
  'AAPU01': 'Drosophila mojavensis',
  'AAQB01': 'Drosophila willistoni',
  'AASR01': 'Drosophila simulans',
  'AAST01': 'Drosophila simulans',
  'AASU01': 'Drosophila simulans',
  'AASW01': 'Drosophila simulans',
  'AEAC01': 'Harpegnathos saltator',
  'AFFI02': 'Drosophila takahashii',
  'AFPQ02': 'Drosophila eugracilis',
  'AJWK01': 'Lutzomyia longipalpis',
  'BAAB01': 'Bombyx mori',
  'BAGR01': 'Plutella xylostella',
  'BDMG01': 'Papilio memnon',
  'BDQP01': 'Drosophila obscura',
  'BHDV01': 'Adoxophyes honmai',
  'CAJMZR01': 'Tachina fera',
  'CAJMZS01': 'Tachina fera',
  'CAJMZT01': 'Xylota sylvarum',
  'CAJMZU01': 'Amphipyra tragopoginis',
  'CAJMZV01': 'Amphipyra tragopoginis',
  'CAJMZW01': 'Colias croceus',
  'CAJMZY01': 'Deilephila porcellus',
  'CAJNAA01': 'Ennomos fuscantarius',
  'CAJNAB01': 'Laothoe populi',
  'CAJNAC01': 'Lysandra coridon',
  'CAJNAD01': 'Laothoe populi',
  'CAJNAE01': 'Lysandra coridon',
  'CAJNAH01': 'Melitaea cinxia',
  'CAJNAI01': 'Nymphalis polychloros',
  'CAJNAK01': 'Spilosoma lubricipeda',
  'CAJNAL01': 'Spilosoma lubricipeda',
  'CAJNAM01': 'Tinea trinotella',
  'CAJNAN01': 'Tinea trinotella',
  'CAJNIT01': 'Eristalis tenax',
  'CAJNIW01': 'Pieris napi',
  'CAJNIX01': 'Pieris napi',
  'JADMLL01': 'Columbicola columbae',
  'JAEMVK01': 'Drosophila virilis',
  'JAEQML01': 'Pissodes strobi',
  'JAFDOW01': 'Bradysia odoriphaga',
  'JAFDUZ01': 'Hestina assimilis',
  'OENV01': 'Bicyclus anynana',
  'OEOA01': 'Spodoptera frugiperda',
  'VWMZ01': 'Bactrocera tryoni',
  'AAGE02': 'Aedes aegypti',
  'AAIZ01': 'Drosophila persimilis',
  'AAKO01': 'Drosophila sechellia',
  'AANI01': 'Drosophila virilis',
  'AAPP01': 'Drosophila ananassae',
  'AASS01': 'Drosophila simulans',
  'AASV01': 'Drosophila simulans',
  'BABH01': 'Bombyx mori',
  'BBJD01': 'Papilio polytes',
  'BDMF01': 'Papilio memnon',
  'BGZK01': 'Eumeta japonica',
  'BHWX01': 'Bombyx mori',
  'BNES01': 'Trypoxylus dichotomus',
  'CAACVG01': 'Callosobruchus maculatus',
  'CAACXJ01': 'Drosophila subobscura',
  'CABEGB01': 'Crematogaster levior',
  'CABPRJ01': 'Cinara cedri',
  'CACRSI01': 'Ophraella communa',
  'CACRWG01': 'Oryctes borbonicus',
  'CACTIC01': 'Danaus chrysippus',
  'CACTID01': 'Danaus chrysippus',
  'CADCXF01': 'Aphantopus hyperantus',
  'CADEBC01': 'Arctia plantaginis',
  'CADEBD01': 'Arctia plantaginis',
  'CAHPSY01': 'Drosophila subobscura',
  'CAJHJT01': 'Ceratitis capitata',
  'CAJOBZ01': 'Pieris macdunnoughi',
  'CAJOSJ01': 'Hecatera dysodea',
  'CAJOSM01': 'Pyrochroa serraticornis',
  'CAJOSN01': 'Maniola jurtina',
  'CAJOSP01': 'Maniola jurtina',
  'CAJOSR01': 'Lysandra bellargus',
  'CAJOSU01': 'Mimas tiliae',
  'CAJOSV01': 'Lycaena phlaeas',
  'CAJOSW01': 'Lysandra bellargus',
  'CAJOSY01': 'Atethmia centrago',
  'CAJOSZ01': 'Pheosia tremula',
  'CAJOTA01': 'Pheosia tremula',
  'CAJPHX01': 'Abrostola tripartita',
  'CAJPHY01': 'Vespula germanica',
  'CAJPHZ01': 'Vespula germanica',
  'CAJPIA01': 'Abrostola tripartita',
  'CAJPIB01': 'Rhagonycha fulva',
  'FZQP02': 'Leptidea sinapis',
  'JACGXX01': 'Helicoverpa armigera',
  'JADKZE01': 'Drosophila nasuta',
  'JAEVLP01': 'Pogonomyrmex californicus',
  'JAFELO01': 'Eumaeus atala',
  'UBJT01': 'Drosophila novamexicana',
  'UEJX01': 'Drosophila americana',
  'AFFD02': 'Drosophila biarmipes',
  'AFFE02': 'Drosophila bipectinata',
  'AFFF02': 'Drosophila elegans',
  'AFFG02': 'Drosophila ficusphila',
  'AFFH02': 'Drosophila kikkawai',
  'AFPP02': 'Drosophila rhopaloa',
  'ANCD01': 'Chilo suppressalis',
  'APCI01': 'Anopheles funestus',
  'APGK01': 'Dendroctonus ponderosae',
  'APGL01': 'Dendroctonus ponderosae',
  'BABU01': 'Bombyx mori',
  'BBSX02': 'Monomorium pharaonis',
  'CACRWH01': 'Marronus borbonicus',
  'CADCXM02': 'Maniola hyperantus',
  'CAJPIC01': 'Rhagonycha fulva',
  'CAJQET01': 'Vespula vulgaris',
  'CAJQEV01': 'Plebejus argus',
  'CAJQEW01': 'Pheosia gnoma',
  'CAJQEY01': 'Fabriciana adippe',
  'CAJQEZ01': 'Anthocharis cardamines',
  'CAJQFA01': 'Fabriciana adippe',
  'CAJQFB01': 'Pheosia gnoma',
  'CAJQFE01': 'Leptidea sinapis',
  'CAJQFF01': 'Biston betularia',
  'CAJQFG01': 'Glaucopsyche alexis',
  'CAJQFH01': 'Erannis defoliaria',
  'CAJQFM01': 'Glaucopsyche alexis',
  'CAJQFN01': 'Anthocharis cardamines',
  'CAJQFP01': 'Leptidea sinapis',
  'CAJQFS01': 'Vespula vulgaris',
  'CAJQFU01': 'Pieris napi',
  'CAJQFW01': 'Chrysoperla carnea',
  'CAJQFX01': 'Ochropleura plecta',
  'CAJQFY01': 'Clostera curtula',
  'CAJVRO01': 'Apoderus coryli',
  'CAJVRP01': 'Peribatodes rhomboidaria',
  'CAJVRR01': 'Peribatodes rhomboidaria',
  'CAJVRU01': 'Furcula furcula',
  'CAJVRW01': 'Pterostichus madidus',
  'CAJVRX01': 'Pammene fasciana',
  'JADODV01': 'Vandiemenella viatica',
  'JADODW01': 'Vandiemenella viatica',
  'JADODX01': 'Vandiemenella viatica',
  'JADODY01': 'Vandiemenella viatica',
  'JAECZZ02': 'Drosophila santomea',
  'JAEDAA02': 'Drosophila teissieri',
  'JAEDAB02': 'Drosophila yakuba',
  'JAEDAC02': 'Drosophila yakuba',
  'JAFDOQ01': 'Aedes albopictus',
  'PQWD01': 'Leucinodes orbonalis',
  'CAJQFZ01': 'Ochropleura plecta',
  'CAJQGA01': 'Chrysoperla carnea',
  'CAJQGB01': 'Autographa pulchrina',
  'CAJQGC01': 'Schrankia costaestrigalis',
  'CAJQGD01': 'Schrankia costaestrigalis',
  'JAANHZ01': 'Acromyrmex insinuator',
  'JADFFJ01': 'Anopheles coluzzii',
  'JADOXM01': 'Nilaparvata lugens',
  'JAECWG01': 'Drosophila subpulchrella',
  'JAECWH01': 'Drosophila tropicalis',
  'JAECWI01': 'Drosophila equinoxialis',
  'JAECWJ01': 'Drosophila sturtevanti',
  'JAECWK01': 'Drosophila varians',
  'JAECWL01': 'Drosophila ercepeae',
  'JAECWM01': 'Drosophila oshimai',
  'JAECWN01': 'Drosophila quadrilineata',
  'JAECWP01': 'Drosophila sucinea',
  'JAECWQ01': 'Drosophila repletoides',
  'JAECWR01': 'Drosophila pruinosa',
  'JAECWS01': 'Drosophila ambigua',
  'JAECWT01': 'Drosophila tristis',
  'JAECWU01': 'Chymomyza costata',
  'JAECWV01': 'Drosophila triauraria',
  'JAECWW01': 'Drosophila obscura',
  'JAECWX01': 'Drosophila arawakana',

In [17]:
len(prefix_gregarina), len(prefix_insecta), len(prefix_annelida), len(prefix_nematoda), len(prefix_trematoda), len(prefix_cestoda), len(prefix_fish)

(6, 6896, 142, 600, 63, 33, 4259)

In [24]:
file = open("data/nosema.txt", "r")
file.readline()
sequence = file.readline()
file.close()
sequence

'ggccagccgccgcggtttttccagctccaggagcgtctacgggggttgctgcagttaaaaggtccgtagtcgggccggggtggggaaagggggcggggggaggggggtgctcgggcggggtcgtgtggggcggacggggggcgggggatttgggggctaggggtgaaatccggcgacccgcggtggaccggcagaggcgaaggcgccggcctgggacgctctctctgatcaaggacgagggccggaggagcgaaggggattagagaccgctgtagttccggcggtaaacgatgccgacagggcggcgggggggggggctgcgcgggggtcgaagggaacccgagtggcgggctctggggagagtatggtcgaagtgggaaacttaacggaaattgacggagggacaccaccaggagtggagcttgcggcttaatttgactcaacgcggggcagcttaccaggggtggacgccgcggggatcggcgggggggggggtgaatcggctgggagtggtgcatggccgttgctggcccgtggggtgacctgtctggtcgactgcgctaacgggcgcgacctcggcgggggggggggactgccagcgtggaggggggggaagggggaggcgataacaggtccgtgatgccctcggatgtcctgggctgcacgcgcgctacagtgcgcgcaggtgtgggggggggggggggagcggcgcgcgcgggggatggacggctgggaggccgtcctgaacgcggaggggggggggggg\n'

In [34]:
for key, item in prefix_gregarina.items():
    print(item)
    key = f'WGS_VDB://{key}'
    # print(key)
    globals()[f"request_{taxon}_{key}"] = run_blast(sequence=sequence, programm="blastn", database=key, wait=False)

Ascogregarina taiwanensis
NCBI initial response: 200
RID: 0ESVZTXE016 | Estimated wait: 17 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=0ESVZTXE016
Gregarina niphandrodes
NCBI initial response: 200
RID: 0ESW1MEN016 | Estimated wait: 17 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=0ESW1MEN016
Porospora cf. gigantea A
NCBI initial response: 200
RID: 0ESW2RXP013 | Estimated wait: 10 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=0ESW2RXP013
Porospora cf. gigantea B
NCBI initial response: 200
RID: 0ESW3KY4013 | Estimated wait: 10 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=0ESW3KY4013
Ophryocystis elektroscirrha
NCBI initial response: 200
RID: 0ESW4880016 | Estimated wait: 17 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=0ESW4880016
Leidyana gryllorum
NCBI initial response: 200
RID: 0ESW56MH013 | Estimated wait: 10 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=0ESW56MH013

In [35]:
from main import wait_for_blast_results
result = wait_for_blast_results('0EVC4F7Z013')

In [43]:
result

[self.subj_id='NW_003520041.1', self.subj_name='Dictyostelium purpureum unplaced genomic scaffold DICPUscaffold_712,', self.subj_len=7291, self.subj_range=(961, 1076), self.score='341', self.e_value='7e-179', self.identities=86, self.align_len=611, self.query_align='TTACTTTGAGGAAATTGGAGTGTTTAAAGCAGGCGTGCGCCTGGACAGGACAGCATGGAATAATGGAATAGGACG-GCGGTTCTATTTCGTTGGTT-GGGGA-CCGTGGTAATGGTTGATAGGGACAGTTGGGGGCATTGGTATTGCG-CGGTCAGAGGTGAAATTCTTGGATTCGCGCAAGACACACAAGCGCGAAAGCATCTGCCAAGGATGTTTTCATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTCT-AACCGTAAACGATGCCGACGGGGGAGCGG-CGGA-T--AGCATG-TGCTGTCGTCGCGAC-CCGCA-GAGAAATCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACATGGA-AGGATTGACAGATTGATAGCGCTTTCAAGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCT---C-TGCGGGAT-GTTGGGT-GCCGTGTGCTGTTTCATGGGCTCTCTGCCC-GGACTGCCCGCTTCAAGCGGCGGGAAGTTGGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACCGAGACAGAGAGTTGTGG-C-TGGTCCGAGAG--C-GGCTAATCA-G-GAAACTCAGTCGTGCTGGGGATAGACCGTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGGACGTGTTAGTGAGGGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCA-TTTTATACAGTGAAACTGCGAATGGCTCATTATATCAGTTAAAATTCATTTGAGAGTTGGA-TTTACTACTTGGATAACCGTGGTAATTCTAGAGCTAATACATGC--GCAGAG-CCCGACTTCTGG-GCGGGTGTATTTATTAGATAA-CAA-C--CGTCTGTGCGCAAGC-ACGTTGGGGAGTCATAATAACTTGTCGGATCGCATGGCTTTG-GCCGGCGACGTTTCAAAGAAATTTCTGCCCTATCAACTTACGATGGTAGGATAGAGGCCTACCATGGTTGTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAAGAAATATCAATGCGGGGCCCTAT-GGGTCTGC-AATTGGA-T-AG--CAAGTTAAAGG----AGGGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGG-AATTCCAGCTCCAATAGCGAATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGT', self.sbjct_align='TTACCTTGAGAAAATTAGAGTGTTCAAAGCAGGCCTGTGCCTGAATACATTAGCATGGAATAATAAAATAGGACGTGCGGTTCTATTTTGTTGGTTTCTAGAGTCGCCGTAATGATTAATAGGGATAGTTGGGGGCATTGGTATTGAGTCGCT-AGAGGTGAAATTCTTGGATTGACTCAAGACCAACTACTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGAAGGTTAGGGGATCGAAAACGATCAGATACCGTTGTAGTCTTAACAGTAAACTATGCCGACTAGGGATCGGGCAATCTCAAACATGATG-TGTTG-CTCGGCACCTTACGAGAAATC-AAAGTCTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCACCACCAGGTGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGGAAACTCACCAGGTCCAGACATAACTAGGATTGACAGATTGATAGCTCTTTCATGATTTTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCTTAACCTGCTAAATAGCCAGGCCGGCTTTCGCTGGT-CGCCGGCT-TCTTAGAGGGACTGTCAGCGTCTAGCTGACGGAAGTTTGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACAGAGCCAGCGAGTTTTTTTCCTTGGCCGGAAGGTCTGGGTAATCTTGTGAAACTCTGTCGTGCTGGGGATAGAGCATTGCAATTATTGCTCTTCAACGAGGAATACCTAGTAAGCGTGAGTCATCAGCTCGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTACTACCGATTGAATGGCTTAGTGAGGGCTTGTCTCAAAGACTAAGCCATGCATGTCTAAGTATAAACAAATTTGTACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAGTTTATTTGA---TGGTACCTTGCTACATGGATAACTGTGGTAATTCTAGAGCTAATACATGCAATCA-AGCCCCGACTTCTGGAAGGGGTGTATTTATTAGATAAAAAACCAACG-CGGCTCGC-CGCTCCCTTGGTGATTCATAATAACTTCTCGAATCGCATGGCCTTGTGCCGGCGATGCTTCATTCAAATATCTGCCCTATCAACTTTCGATGGTAGGATAGAGGCCTACCATGGTTTCAACGGGTAACGGGGAATAAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAATAAATAACAATATAGGGCTCTTTTGGGTCTTATAATTGGAATGAGTACAATTTAAATCCCTTAACGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGT',
 self.subj_id='NW_001916170.1', self.subj_name='Entamoeba histolytica HM-1:IMSS scf_1104750516591 genomic scaffold,', self.subj_len=1154, self.subj_range=(1154, 266), self.score='99', self.e_value='2e-44', self.identities=77, self.align_len=368, self.query_align='ATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGT-CTAACCGTAAACGATGCCGACGGGGGA---GCGGCGG--ATAGCATGTGCTGTCGTC-GC-GACCCGCAGAGAAA--TCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACCGAGACAGAGAGTTGTGG----CTGGTCCG--AGAG-CGGCTAATCAGGAAACTCA--GTCGTG-CTGGGGATAGACCGTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGGACGTGTTAGTGAGGCTGGGGGATT---GT-G--GTGGT-GCTTTG--GCATTACTG-TG--GAG-A-ACCATCAAACTTGGAC-GTCTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAG', self.sbjct_align='ATCAGGAGCGAAAGTCAGAGTTTCGAAGACGATCAGATACCGTCGTAGTTCTGACCATAAACGATGCCAACTGACGATCCGCGTTGGTTCTATAAT-TGACATCGCGGGCAGTCCC-C-GGGAAACCTTTA-AGTCTTTGGGCTCCGGGGGGAGTATGGTTGCAAAGCTGAAACTTAAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGTTTAATTCGACTCAACACGGGAAAACTCACCCGGCCCGGACACTGTGAGGATTGACAGATTGATAGCTCTTTCTTGATTCGGTGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTTAATTCCGATAACGAACGAGACGCAATAACAGGTCTGTGATGCCCTTAGATGTCCGGGGCCACACGTGCGCTACAATGACGGTGCCAGCGAGT-CTGGAAACCTGGCCCGAAAGGGTTGGGCAAACTGTTTCATCACCGTCGTGACT-GGGATCGGGGCTTGCAATTATTCCCCGTGAACGAGGAATTCCTGGTAAGTGCAAGTCATAAGCTTGCGCTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTACTACCGATTGAATGGTTTAGTGAGGTCGTTGGATTGGCGTCGTTGTAGTGGCTTTGCCGCTCGACTGATGCTGAGAAGATGACCTAA-TTTGACTATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAG',
 self.subj_id='NW_003520110.1', self.subj_name='Dictyostelium purpureum unplaced genomic scaffold DICPUscaffold_786,', self.subj_len=3987, self.subj_range=(1714, 853), self.score='47', self.e_value='2e-15', self.identities=87, self.align_len=82, self.query_align='CATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTCTAACCG-TAAACGATGCCGACGGGGGAGCGGCGGATAGCATGTGC---TGTCGTCGCGACCCGCAGAGAAATCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCA-GGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACATGG-AAGGATTGACAGATTGATAGCGCTTTCAAGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCTCCTGCCCTATCAACTTACGATGGTA--GG-ATAGAGGCCTACCATGGTTGTAAC-GGGTAACGGGGAATTAGGGTTCGATTCCGGAGA-GGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACAC-GGGGAGGTAGTGACAAGAAATATCAATGCGGGGCCC-TATGGGTCTGCAATTGGA-T-AGCA-AG--TTAAAGGAGGGAGG-A--ACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGG-AATTCCAGCTCCAATAGCGAATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTGGACTGCCCGCTTCAAGC-GGCGGGAAGTTGGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACCGAGA-CAGAGAG-TTG-TGG-CTGGTCCGAGAGCGGCTAATCAG--GAAACT-CAGTCGTG-CTGGGGATAGACCGTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCATT-TTATACAGTGAAACTGCGAATGGCTCATTATATCAGT', self.sbjct_align='CATTAATCAAGAACGAAAGTTTGGGGATCGAAGACGATCAGATACCGTCGTAGTCCAAACTATAAACTATGTCGACCAGGGATCGGCTAATATTTTTTTAAAATTTAGTCGGCACCTTGTGAGAAATCATGAGTGTTTAGATTCCGGGGGGAGTATGGTCGCAAGTCTGAAACTTAAAGGAATTGACGGAAGGGCAC-ACAATGGAGTGGAGCCTGCGGCTTAATTTGACTCAACTCGGGAAAACTTACCAAGCTAAGATATAGTAAGGATTGACAGACTAAAAGATCTTTCATGATTCTATAAGTGGTGGTGCATGGTCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTCAATTCCGATAACGGACGAGACCTCCTGCCCTATCAACTTTCGATGGTACGGGTATTG-GGCCTACCATGGTTGTAACGGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGGAGCCTGAGAAATGGCTACCACTTCTACGGAAGGCAGCAGGCGCGCAAATTACTCAATCCCAATACGGGGGAAGTAGTGACAATAAATATCAATACCTATCCTTTAACGGAGGGCAATTGAAATGAACACAAAATTAAAACTCTTAATTAACACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCATATACTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTGGACTACCTGCCTCAAGCAGGC-GGAAGTCCGAGGCAATAACAGGTCTGTGATGCCCTTAGATACCTTGGGCCGCACGCGCGCTACAATG-CAGATAGCAAAAAGGTTCCTGGTCTGGAAAGATTG-GG-TAATCAATTGAATTTTCTG-CGTAACT-GGGATTGATCTTTGTAATTATTGATCATCAACGAGGAATTCCTTGTAAGCGTAAGTCATTACCTTATGCTGAATATGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAA--ATTCTTGTACGATGAAACTGCAGACGGCTCATTACAACAGT',
 self.subj_id='NW_003520135.1', self.subj_name='Dictyostelium purpureum unplaced genomic scaffold DICPUscaffold_823,', self.subj_len=3170, self.subj_range=(2061, 2257), self.score='47', self.e_value='2e-15', self.identities=87, self.align_len=82, self.query_align='CTGCCCTATCAACTTACGATGGTAGGATAGAGGCCTACCATGGTTGTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAAGAAATATCAATGCGGGGCCCTATGGGTCTGCAATTGGA-T-AGCA-AG-TTAAAGGAGGGAGG-A--ACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGG-AATTCCAGCTCCAATAGCGAATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTGAGAAATCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCA-GGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACATGG-AAGGATTGACAGATTGATAGCGCTTTCAAGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCTCGGACTGCCCGCTTCAAGC-GGCGGGAAGTTGGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACCGAGA-CAGAGAG-TTG-TGG-CTGGTCCGAGAGCGGCTAATCAG--GAAACT-CAGTCGTG-CTGGGGATAGACCGTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCATT-TTATACAGTGAAACTGCGAATGGCTCATTATATCAGT', self.sbjct_align='CTGCCCTATCAACTTTCGATGGTACGGTATTGGCCTACCATGGTTGTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAATGGCTACCACTTCTACGGAAGGCAGCAGGCGCGCAAATTACTCAATCCCAATACGGGGAAGTAGTGACAATAAATATCAATACCTATCCTTAACGGAGGGCAATTGAAATGAACACAAATTAAAACTCTTAATTAACACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCATATACTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTGAGAAATCATGAGTGTTTAGATTCCGGGGGGAGTATGGTCGCAAGTCTGAAACTTAAAGGAATTGACGGAAGGGCAC-ACAATGGAGTGGAGCCTGCGGCTTAATTTGACTCAACTCGGGAAAACTTACCAAGCTAAGATATAGTAAGGATTGACAGACTAAAAGATCTTTCATGATTCTATAAGTGGTGGTGCATGGTCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTCAATTCCGATAACGGACGAGACCTCGGACTACCTGCCTCAAGCAGGC-GGAAGTCCGAGGCAATAACAGGTCTGTGATGCCCTTAGATACCTTGGGCCGCACGCGCGCTACAATG-CAGATAGCAAAAAGGTTCCTGGTCTGGAAAGATTG-GG-TAATCAATTGAATTTTCTG-CGTAACT-GGGATTGATCTTTGTAATTATTGATCATCAACGAGGAATTCCTTGTAAGCGTAAGTCATTACCTTATGCTGAATATGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAA--ATTCTTGTACGATGAAACTGCAGACGGCTCATTACAACAGT',
 self.subj_id='NW_003102029.1', self.subj_name='Dictyostelium discoideum AX4 chromosome Un chrUn_00036, whole', self.subj_len=39796, self.subj_range=(30647, 30519), self.score='48', self.e_value='5e-16', self.identities=78, self.align_len=148, self.query_align='CTGCCCTATCAACTTACGATGGTAGGATAGAGGCCTACCATGGTTGTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAAGAAATATCAATGCGGGGCCCTATGGGTCTGCAATTGGA-T-AGCA-AG-TTAAAGGAGGGAGG-A--ACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGG-AATTCCAGCTCCAATAGCGAATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTCATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGT-CTAACCGTAAACGATGCCGACGGGGGAGCGGCGGATAGCATGTGC----TGTCGTCGCGACCCGCAGAGAAATCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCA-GGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACATGG-AAGGATTGACAGATTGATAGCGCTTTCAAGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCTCGGACTGCCCGCTTCAAGC-GGCGGGAAGTTGGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACCGAGACAGAGAGTTGTGGCTGGTCCG-A--GAGCGGCTAATCAG--GAAACTCAGTCGTG-CTGGGGATAGACCGTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCATT-TTATACAGTGAAACTGCGAATGGCTCATTATATCAGTTA-AAATTCATTTGAGAGTTGGATTT-ACTACTTGGATAACCGTGGTAATTCTAGAGCTAATACAT', self.sbjct_align='CTGCCCTATCAACTTTCGATGGTACGGTATTGGCCTACCATGGTTGTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAATGGCTACCACTTCTACGGAAGGCAGCAGGCGCGCAAATTACTCAATCCCAATACGGGGAAGTAGTGACAATAAATATCAATACCTATCCTTTTTGGAGGGCAATTGAAATGAACACAAATTAAAACTCTTAATTAACACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCATATACTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTCATTAATCAAGAACGAAAGTTTGGGGATCGAAGACGATCAGATACCGTCGTAGTCCAAACTATAAACTATGTCGACCAGGGATCGG-TTAAAATTTTTTCAAAATTTAATCGGCACCTTGTGAGAAATCATGAGTGTTTAGATTCCGGGGGGAGTATGGTCGCAAGTCTGAAACTTAAAGGAATTGACGGAAGGGCAC-ACAATGGAGTGGAGCCTGCGGCTTAATTTGACTCAACTCGGGAAAACTTACCAAGCTAAGATATAGTAAGGATTGACAGACTAAAAGATCTTTCATGATTCTATAAGTGGTGGTGCATGGTCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTCAATTCCGATAACGGACGAGACCTCGGACTACCTGCCTCAAGCAGGC-GGAAGTCCGAGGCAATAACAGGTCTGTGATGCCCTTAGATACCTTGGGCCGCACGCGCGCTACAATGTAGGAAACAAAAAGGC-TC-CTGGTCCGGAAGGATTGGGTAATCATTTGAATTTCCTACGTAACTGGGCTT-GATCTTTGTAATTATTGATCATAAACGAGGAATTCCTTGTAAGCGTAAGTCATTACCTTATGCTGAATATGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAA--ATTCTTGTACGATGAAACTGCAGACGGCTCATTACAACAGTGATAAACTAAT-AGACTTTCGGGTTTTACCTTTTGGATAACCGCAGTAAATCGGG-GCTAATACAT',
 self.subj_id='NW_001853158.1', self.subj_name='Entamoeba dispar SAW760 scf_1105229458369 genomic scaffold, whole', self.subj_len=1027, self.subj_range=(826, 350), self.score='41', self.e_value='4e-12', self.identities=91, self.align_len=56, self.query_align='AGAGAAATCTAGAGTTTTTGG-GTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTA-TGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGCATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTC-TAACCGTAAACGATGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTG', self.sbjct_align='AGAGAAATCTTGAGTTTATGGACTTCAGGGGGGAGTATGGTCACAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCAC-ACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAAGACCGAACAGTAGAAGGAATGACAGATTAAGAGTTCTTTCATGATT-TATTGGGTAGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCAGGTTAATTCCGGTAACGAACGAGACTTGGAATTATTTGTTTTGAACGAGGAATTCCTTGTAATATCGAGTCATTAACTCGAGATGAATACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATTGCATTAATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTCCTAACTATAAACGATGGCAATAACAGGTCTGTGATGCCCTTAGACATCTTGGGCCGCACGCGCGCTACAATG',
 self.subj_id='NW_001858935.1', self.subj_name='Entamoeba dispar SAW760 scf_1108853436961 genomic scaffold, whole', self.subj_len=580, self.subj_range=(579, 105), self.score='41', self.e_value='4e-12', self.identities=91, self.align_len=56, self.query_align='AGAGAAATCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTA-TGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTG', self.sbjct_align='AGAGAAATCTTGAGTTTATGGCTTC-AGGGGGAGTATGGTCACAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCAC-ACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAAGACCGAACAGTAGAAGGAATGACAGATTAAGAGTTCTTTCATGATT-TATTGGGTAGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCAGGTTAATTCCGGTAACGAACGAGACGCAATAACAGGTCTGTGATGCCCTTAGACATCTTGGGCCGCACGCGCGCTACAATG',
 self.subj_id='NW_004440442.1', self.subj_name='Entamoeba invadens IP1 unplaced genomic scaffold scaff_1105074726431,', self.subj_len=1078, self.subj_range=(413, 508), self.score='59', self.e_value='4e-22', self.identities=82, self.align_len=138, self.query_align='AGAGAAATCTAGAGTTTTTGG-GTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTA-TGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGG-AATTCCAGCTCCAATAGCGAATATTAAAGTTG-T-TGCAGTTAAAAAGCTCGTAGTAGAGGTGAAATTCTTGGATTCGC-GCAAGACACACAAGCGCGAAAGCATCT-GC-CAAGGATGTTTTCATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTC-TAACCGTAAACGATG', self.sbjct_align='AGAGAAATCTTGAGTTTATGGACTTC-AGGGGGAGTATGGTCACAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCAC-ACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAAGACCGAACAGTAGAAGGAATGACAGATTAAGAGTTCTTTCATGATT-TATTGGGTAGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCAGGTTAATTCCGGTAACGAACGAGACCAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGTGTATATTAAAGTTGCTGTG-A-TTAAAACGCTCGTAGTAGAGGTGAAAATCCATGA-TCGCTATAAGATGCACGAGAGCGAAAGCATTTCACTCAA--CTGTGTCCATTAATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTCCTAACTATAAACGATG',
 self.subj_id='NW_001865037.1', self.subj_name='Entamoeba dispar SAW760 scf_1108853449247 genomic scaffold, whole', self.subj_len=974, self.subj_range=(131, 603), self.score='41', self.e_value='4e-12', self.identities=92, self.align_len=53, self.query_align='AGAGAAATCTAGAGTTTTTGG-GTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTA-TGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACA', self.sbjct_align='AGAGAAATCTTGAGTTTATGGACTTC-AGGGGGAGTATGGTCACAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCA-CACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAAGACCGAACAGTAGAAGGAATGACAGATTAAGAGTTCTTTCATGATT-TATTGGGTAGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCAGGTTAATTCCGGTAACGAACGAGACTTGGAATTATTTGTTTTGAACGAGGAATTCCTTGTAATATCGAGTCATTAACTCGAGATGAATACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATTGGCAATAACAGGTCTGTGATGCCCTTAGACATCTTGGGCCGCACGCGCGCTACA',
 self.subj_id='NW_001865020.1', self.subj_name='Entamoeba dispar SAW760 scf_1108853449213 genomic scaffold, whole', self.subj_len=956, self.subj_range=(136, 608), self.score='41', self.e_value='4e-12', self.identities=92, self.align_len=53, self.query_align='AGAGAAATCTAGAGTTTTTGG-GTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTA-TGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACA', self.sbjct_align='AGAGAAATCTTGAGTTTATGGACTTC-AGGGGGAGTATGGTCACAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCA-CACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAAGACCGAACAGTAGAAGGAATGACAGATTAAGAGTTCTTTCATGATT-TATTGGGTAGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCAGGTTAATTCCGGTAACGAACGAGACTTGGAATTATTTGTTTTGAACGAGGAATTCCTTGTAATATCGAGTCATTAACTCGAGATGAATACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATTGGCAATAACAGGTCTGTGATGCCCTTAGACATCTTGGGCCGCACGCGCGCTACA',
 self.subj_id='NW_001864991.1', self.subj_name='Entamoeba dispar SAW760 scf_1108853449155 genomic scaffold, whole', self.subj_len=943, self.subj_range=(136, 608), self.score='41', self.e_value='4e-12', self.identities=92, self.align_len=53, self.query_align='AGAGAAATCTAGAGTTTTTGG-GTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACA-TGGAAGGATTGACAGATTGATAGCGCTTTCAAGATTCTA-TGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACA', self.sbjct_align='AGAGAAATCTTGAGTTTATGGACTTC-AGGGGGAGTATGGTCACAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCA-CACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAAGACCGAACAGTAGAAGGAATGACAGATTAAGAGTTCTTTCATGATT-TATTGGGTAGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCAGGTTAATTCCGGTAACGAACGAGACTTGGAATTATTTGTTTTGAACGAGGAATTCCTTGTAATATCGAGTCATTAACTCGAGATGAATACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATTGGCAATAACAGGTCTGTGATGCCCTTAGACATCTTGGGCCGCACGCGCGCTACA',

In [ ]:
self.subj_id='NW_003520041.1', self.subj_name='Dictyostelium purpureum unplaced genomic scaffold DICPUscaffold_712,', self.subj_len=7291, self.subj_range=(961, 1076), self.score='341', self.e_value='7e-179', self.identities=86, self.align_len=611, self.query_align='TTACTTTGAGGAAATTGGAGTGTTTAAAGCAGGCGTGCGCCTGGACAGGACAGCATGGAATAATGGAATAGGACG-GCGGTTCTATTTCGTTGGTT-GGGGA-CCGTGGTAATGGTTGATAGGGACAGTTGGGGGCATTGGTATTGCG-CGGTCAGAGGTGAAATTCTTGGATTCGCGCAAGACACACAAGCGCGAAAGCATCTGCCAAGGATGTTTTCATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTCT-AACCGTAAACGATGCCGACGGGGGAGCGG-CGGA-T--AGCATG-TGCTGTCGTCGCGAC-CCGCA-GAGAAATCTAGAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTGAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCACCAGGTCCAGACATGGA-AGGATTGACAGATTGATAGCGCTTTCAAGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCT---C-TGCGGGAT-GTTGGGT-GCCGTGTGCTGTTTCATGGGCTCTCTGCCC-GGACTGCCCGCTTCAAGCGGCGGGAAGTTGGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACCGAGACAGAGAGTTGTGG-C-TGGTCCGAGAG--C-GGCTAATCA-G-GAAACTCAGTCGTGCTGGGGATAGACCGTTGGAATTGTTGGTCTTGAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGATACTACCGATTGGACGTGTTAGTGAGGGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCA-TTTTATACAGTGAAACTGCGAATGGCTCATTATATCAGTTAAAATTCATTTGAGAGTTGGA-TTTACTACTTGGATAACCGTGGTAATTCTAGAGCTAATACATGC--GCAGAG-CCCGACTTCTGG-GCGGGTGTATTTATTAGATAA-CAA-C--CGTCTGTGCGCAAGC-ACGTTGGGGAGTCATAATAACTTGTCGGATCGCATGGCTTTG-GCCGGCGACGTTTCAAAGAAATTTCTGCCCTATCAACTTACGATGGTAGGATAGAGGCCTACCATGGTTGTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAAGAAATATCAATGCGGGGCCCTAT-GGGTCTGC-AATTGGA-T-AG--CAAGTTAAAGG----AGGGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGG-AATTCCAGCTCCAATAGCGAATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGT', self.sbjct_align='TTACCTTGAGAAAATTAGAGTGTTCAAAGCAGGCCTGTGCCTGAATACATTAGCATGGAATAATAAAATAGGACGTGCGGTTCTATTTTGTTGGTTTCTAGAGTCGCCGTAATGATTAATAGGGATAGTTGGGGGCATTGGTATTGAGTCGCT-AGAGGTGAAATTCTTGGATTGACTCAAGACCAACTACTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGAAGGTTAGGGGATCGAAAACGATCAGATACCGTTGTAGTCTTAACAGTAAACTATGCCGACTAGGGATCGGGCAATCTCAAACATGATG-TGTTG-CTCGGCACCTTACGAGAAATC-AAAGTCTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCACCACCAGGTGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGGAAACTCACCAGGTCCAGACATAACTAGGATTGACAGATTGATAGCTCTTTCATGATTTTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGAGACCTTAACCTGCTAAATAGCCAGGCCGGCTTTCGCTGGT-CGCCGGCT-TCTTAGAGGGACTGTCAGCGTCTAGCTGACGGAAGTTTGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACAGAGCCAGCGAGTTTTTTTCCTTGGCCGGAAGGTCTGGGTAATCTTGTGAAACTCTGTCGTGCTGGGGATAGAGCATTGCAATTATTGCTCTTCAACGAGGAATACCTAGTAAGCGTGAGTCATCAGCTCGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTACTACCGATTGAATGGCTTAGTGAGGGCTTGTCTCAAAGACTAAGCCATGCATGTCTAAGTATAAACAAATTTGTACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAGTTTATTTGA---TGGTACCTTGCTACATGGATAACTGTGGTAATTCTAGAGCTAATACATGCAATCA-AGCCCCGACTTCTGGAAGGGGTGTATTTATTAGATAAAAAACCAACG-CGGCTCGC-CGCTCCCTTGGTGATTCATAATAACTTCTCGAATCGCATGGCCTTGTGCCGGCGATGCTTCATTCAAATATCTGCCCTATCAACTTTCGATGGTAGGATAGAGGCCTACCATGGTTTCAACGGGTAACGGGGAATAAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAATAAATAACAATATAGGGCTCTTTTGGGTCTTATAATTGGAATGAGTACAATTTAAATCCCTTAACGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGT'

In [36]:
dfs = result
dataframe = pd.DataFrame([{
    "description": df.subj_name,
    "score": df.score,
    "e_value": df.e_value,
    "identities": df.identities,
    "alignment_length": df.align_len,
    "query_alignment": df.query_align,
    "subject_alignment": df.sbjct_align,
    "subj_range": df.subj_range,
    "subject_length": df.subj_len,
    "accession": df.subj_id,
} for df in dfs])
display(dataframe.drop(columns=['query_alignment', 'subject_alignment']).head())
dataframe[['query_alignment', 'subject_alignment']].head()

,description,score,e_value,identities,alignment_length,subj_range,subject_length,accession
0,Dictyostelium purpureum unplaced genomic scaff...,341,7e-179,86,611,"(961, 1076)",7291,NW_003520041.1
1,Entamoeba histolytica HM-1:IMSS scf_1104750516...,99,2e-44,77,368,"(1154, 266)",1154,NW_001916170.1
2,Dictyostelium purpureum unplaced genomic scaff...,47,2e-15,87,82,"(1714, 853)",3987,NW_003520110.1
3,Dictyostelium purpureum unplaced genomic scaff...,47,2e-15,87,82,"(2061, 2257)",3170,NW_003520135.1
4,Dictyostelium discoideum AX4 chromosome Un chr...,48,5e-16,78,148,"(30647, 30519)",39796,NW_003102029.1

,query_alignment,subject_alignment
0,TTACTTTGAGGAAATTGGAGTGTTTAAAGCAGGCGTGCGCCTGGAC...,TTACCTTGAGAAAATTAGAGTGTTCAAAGCAGGCCTGTGCCTGAAT...
1,ATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGT...,ATCAGGAGCGAAAGTCAGAGTTTCGAAGACGATCAGATACCGTCGT...
2,CATTGATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACC...,CATTAATCAAGAACGAAAGTTTGGGGATCGAAGACGATCAGATACC...
3,CTGCCCTATCAACTTACGATGGTAGGATAGAGGCCTACCATGGTTG...,CTGCCCTATCAACTTTCGATGGTACGGTATTGGCCTACCATGGTTG...
4,CTGCCCTATCAACTTACGATGGTAGGATAGAGGCCTACCATGGTTG...,CTGCCCTATCAACTTTCGATGGTACGGTATTGGCCTACCATGGTTG...

In [ ]:
file = open('KX214676_Amphiacantha.txt', "w")

In [ ]:
response = requests.post(
            "https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?",
            data={'q': f'&wt=xml&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'})

results = extract_prefix_organism_pairs(response.text)
with open("tests/data/expected_prefixes.txt", "w", encoding="utf-8") as f:
    f.write(results)

TypeError: write() argument must be str, not list

In [ ]:
import sys
n = input()


def main():
    data = input().splitlines()
    n = int(data[0])
    moves = data[1:]

    from_counter = {}
    to_counter = {}

    for move in moves:
        from_addr, to_addr = ' '.join(move.split()[:2]), ' '.join(move.split()[2:])
        from_counter[from_addr] = from_counter.get(from_addr, 0) + 1
        to_counter[to_addr] = to_counter.get(to_addr, 0) + 1

    start, end = None, None

    addresses = set(from_counter.keys()) | set(to_counter.keys())

    for addr in addresses:
        from_count = from_counter.get(addr, 0)
        to_count = to_counter.get(addr, 0)

        if from_count - to_count == 1:
            if start is not None:
                print(-1)
                return
            start = addr
        elif to_count - from_count == 1:
            if end is not None:
                print(-1)
                return
            end = addr
        elif from_count != to_count:
            print(-1)
            return

    if start and end:
        print(start, end)
    else:
        print(-1)

KeyboardInterrupt:

In [52]:
n = int(input())
adresses = []
for i in range(n):
    adresses.append(input())

KeyboardInterrupt: