In [1]:
import requests
import pandas as pd

In [2]:
%load_ext autoreload
%autoreload 2

# BLAST API

In [3]:
from main import run_blast, extract_prefix_organism_pairs, filter_valid_wgs_ids, wait_for_blast_results

In [7]:
sequence = 'MPPLTKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW'
response = run_blast(sequence, programm='tblastn', database='wgs', wait=False, taxon='Vairimorpha')

[WGS index] Found 6 matching entries.
prefixes: [('NZ_ACOL01', 'Vairimorpha ceranae BRL01'), ('ACOL01', 'Vairimorpha ceranae BRL01'), ('ANPH01', 'Vairimorpha apis BRL 01'), ('JPQZ01', 'Vairimorpha ceranae'), ('SMUP01', 'Vairimorpha ceranae'), ('JAWUGJ01', 'Vairimorpha bombi')]
ACOL01: Nosema ceranae BRL01
ANPH01: Nosema apis BRL 01
JAWUGJ01: Vairimorpha bombi
JPQZ01: Nosema ceranae
SMUP01: Nosema ceranae
database: WGS_VDB://ACOL01 WGS_VDB://ANPH01 WGS_VDB://JAWUGJ01 WGS_VDB://JPQZ01 WGS_VDB://SMUP01
NCBI initial response: 200
RID: 07XRW88X016 | Estimated wait: 3 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=07XRW88X016

In [8]:
wait_for_blast_results(response)

[self.subj_id='ACOL01000155.1', self.subj_name='Vairimorpha ceranae BRL01 Nc000155, whole genome shotgun sequence', self.subj_len=8322, self.subj_range=(3963, 3799), self.score='146', self.e_value='7e-13', self.identities=44, self.align_len=55, self.query_align='KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFNRQPVSYQLW',
 self.subj_id='JPQZ01000050.1', self.subj_name='Vairimorpha ceranae strain PA08 1199 NODE_50, whole genome shotgun', self.subj_len=31438, self.subj_range=(5804, 5968), self.score='146', self.e_value='7e-13', self.identities=44, self.align_len=55, self.query_align='KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFNRQPVSYQLW',
 self.subj_id='SMUP01000107.1', self.subj_name='Vairimorpha ceranae strain BRL tig00000215, whole genome shotgun', self.subj_len=91002, self.subj_range=(47461, 47297), self.score='146', self.e_value='7e-13', self.identities=44, self.align_len=55, self.query_align='KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFNRQPVSYQLW',
 self.subj_id='JAWUGJ010000015.1', self.subj_name='Vairimorpha bombi strain VR1 V_bombi_contig15, whole genome shotgun', self.subj_len=138372, self.subj_range=(70110, 70283), self.score='130', self.e_value='1e-10', self.identities=36, self.align_len=58, self.query_align='PLTKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='PIETSYFNRMVDKAFNMLLNKMECLSDTVNEQDGGISFSINNIGEYMFNRQPTSKQLW',
 self.subj_id='ANPH01000692.1', self.subj_name='Vairimorpha apis BRL 01 scf7180000046973_1, whole genome shotgun', self.subj_len=19293, self.subj_range=(13247, 13414), self.score='125', self.e_value='4e-10', self.identities=39, self.align_len=56, self.query_align='TKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='NKYNFNKMIEKGFNTIINMMEKFTDNVSESESSLGFNVEKVGDYLFNRQSASNQLW',
 self.subj_id='ACOL01000021.1', self.subj_name='Vairimorpha ceranae BRL01 Nc000021, whole genome shotgun sequence', self.subj_len=21707, self.subj_range=(7367, 7290), self.score='50', self.e_value='9.0', self.identities=35, self.align_len=26, self.query_align='ISDKFDPFHGDFSEDSGTLSINLKGI', self.sbjct_align='VSIAHDPISGDYMADAGALVVSDNGL',
 self.subj_id='JPQZ01000049.1', self.subj_name='Vairimorpha ceranae strain PA08 1199 NODE_49, whole genome shotgun', self.subj_len=33022, self.subj_range=(7426, 7349), self.score='50', self.e_value='9.0', self.identities=35, self.align_len=26, self.query_align='ISDKFDPFHGDFSEDSGTLSINLKGI', self.sbjct_align='VSIAHDPISGDYMADAGALVVSDNGL',
 self.subj_id='SMUP01000048.1', self.subj_name='Vairimorpha ceranae strain BRL tig00000001, whole genome shotgun', self.subj_len=285139, self.subj_range=(76212, 76289), self.score='50', self.e_value='9.0', self.identities=35, self.align_len=26, self.query_align='ISDKFDPFHGDFSEDSGTLSINLKGI', self.sbjct_align='VSIAHDPISGDYMADAGALVVSDNGL']

In [16]:
sequence = 'MPPLTKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW'
response = run_blast(sequence, programm='tblastn', database='wgs', wait=True, taxon='Vairimorpha')
response

[WGS index] Found 6 matching entries.
prefixes: [('NZ_ACOL01', 'Vairimorpha ceranae BRL01'), ('ACOL01', 'Vairimorpha ceranae BRL01'), ('ANPH01', 'Vairimorpha apis BRL 01'), ('JPQZ01', 'Vairimorpha ceranae'), ('SMUP01', 'Vairimorpha ceranae'), ('JAWUGJ01', 'Vairimorpha bombi')]
ACOL01: Nosema ceranae BRL01
ANPH01: Nosema apis BRL 01
JAWUGJ01: Vairimorpha bombi
JPQZ01: Nosema ceranae
SMUP01: Nosema ceranae
database: WGS_VDB://ACOL01 WGS_VDB://ANPH01 WGS_VDB://JAWUGJ01 WGS_VDB://JPQZ01 WGS_VDB://SMUP01
NCBI initial response: 200
RID: 07XW88JK016 | Estimated wait: 2 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=07XW88JK016
Waiting for BLAST job to complete...

[self.subj_id='ACOL01000155.1', self.subj_name='Vairimorpha ceranae BRL01 Nc000155, whole genome shotgun sequence', self.subj_len=8322, self.subj_range=(3963, 3799), self.score='146', self.e_value='7e-13', self.identities=44, self.align_len=55, self.query_align='KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFNRQPVSYQLW',
 self.subj_id='JPQZ01000050.1', self.subj_name='Vairimorpha ceranae strain PA08 1199 NODE_50, whole genome shotgun', self.subj_len=31438, self.subj_range=(5804, 5968), self.score='146', self.e_value='7e-13', self.identities=44, self.align_len=55, self.query_align='KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFNRQPVSYQLW',
 self.subj_id='SMUP01000107.1', self.subj_name='Vairimorpha ceranae strain BRL tig00000215, whole genome shotgun', self.subj_len=91002, self.subj_range=(47461, 47297), self.score='146', self.e_value='7e-13', self.identities=44, self.align_len=55, self.query_align='KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFNRQPVSYQLW',
 self.subj_id='JAWUGJ010000015.1', self.subj_name='Vairimorpha bombi strain VR1 V_bombi_contig15, whole genome shotgun', self.subj_len=138372, self.subj_range=(70110, 70283), self.score='130', self.e_value='1e-10', self.identities=36, self.align_len=58, self.query_align='PLTKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='PIETSYFNRMVDKAFNMLLNKMECLSDTVNEQDGGISFSINNIGEYMFNRQPTSKQLW',
 self.subj_id='ANPH01000692.1', self.subj_name='Vairimorpha apis BRL 01 scf7180000046973_1, whole genome shotgun', self.subj_len=19293, self.subj_range=(13247, 13414), self.score='125', self.e_value='4e-10', self.identities=39, self.align_len=56, self.query_align='TKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFNKQPSTHQLW', self.sbjct_align='NKYNFNKMIEKGFNTIINMMEKFTDNVSESESSLGFNVEKVGDYLFNRQSASNQLW',
 self.subj_id='ACOL01000021.1', self.subj_name='Vairimorpha ceranae BRL01 Nc000021, whole genome shotgun sequence', self.subj_len=21707, self.subj_range=(7367, 7290), self.score='50', self.e_value='9.0', self.identities=35, self.align_len=26, self.query_align='ISDKFDPFHGDFSEDSGTLSINLKGI', self.sbjct_align='VSIAHDPISGDYMADAGALVVSDNGL',
 self.subj_id='JPQZ01000049.1', self.subj_name='Vairimorpha ceranae strain PA08 1199 NODE_49, whole genome shotgun', self.subj_len=33022, self.subj_range=(7426, 7349), self.score='50', self.e_value='9.0', self.identities=35, self.align_len=26, self.query_align='ISDKFDPFHGDFSEDSGTLSINLKGI', self.sbjct_align='VSIAHDPISGDYMADAGALVVSDNGL',
 self.subj_id='SMUP01000048.1', self.subj_name='Vairimorpha ceranae strain BRL tig00000001, whole genome shotgun', self.subj_len=285139, self.subj_range=(76212, 76289), self.score='50', self.e_value='9.0', self.identities=35, self.align_len=26, self.query_align='ISDKFDPFHGDFSEDSGTLSINLKGI', self.sbjct_align='VSIAHDPISGDYMADAGALVVSDNGL']

Wrap into table

In [17]:
dfs = response
dataframe = pd.DataFrame([{
    "description": df.subj_name,
    "score": df.score,
    "e_value": df.e_value,
    "identities": df.identities,
    "alignment_length": df.align_len,
    "query_alignment": df.query_align,
    "subject_alignment": df.sbjct_align,
    "subj_range": df.subj_range,
    "subject_length": df.subj_len,
    "accession": df.subj_id,
} for df in dfs])
display(dataframe.drop(columns=['query_alignment', 'subject_alignment']).head())
dataframe[['query_alignment', 'subject_alignment']].head()

,description,score,e_value,identities,alignment_length,subj_range,subject_length,accession
0,"Vairimorpha ceranae BRL01 Nc000155, whole geno...",146,7e-13,44,55,"(3963, 3799)",8322,ACOL01000155.1
1,"Vairimorpha ceranae strain PA08 1199 NODE_50, ...",146,7e-13,44,55,"(5804, 5968)",31438,JPQZ01000050.1
2,"Vairimorpha ceranae strain BRL tig00000215, wh...",146,7e-13,44,55,"(47461, 47297)",91002,SMUP01000107.1
3,"Vairimorpha bombi strain VR1 V_bombi_contig15,...",130,1e-10,36,58,"(70110, 70283)",138372,JAWUGJ010000015.1
4,"Vairimorpha apis BRL 01 scf7180000046973_1, wh...",125,4e-10,39,56,"(13247, 13414)",19293,ANPH01000692.1

,query_alignment,subject_alignment
0,KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFN...,KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFN...
1,KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFN...,KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFN...
2,KPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLFN...,KKVYNEMIDRGFNYILDKMEPLSDNITEQEGSLSVNIKDLGEYLFN...
3,PLTKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEY...,PIETSYFNRMVDKAFNMLLNKMECLSDTVNEQDGGISFSINNIGEY...
4,TKPNFSRMIEKAISLISDKFDPFHGDFSEDSGTLSINLKGIGEYLF...,NKYNFNKMIEKGFNTIINMMEKFTDNVSESESSLGFNVEKVGDYLF...

[how to..](https://blast.ncbi.nlm.nih.gov/doc/blast-help/urlapi.html#urlapi)
(делать базовые запросы)

тестим работу экстрактора префиксов..

In [19]:
limit = 1000
rows = 1000
taxon = 'Psyllidae'
response = requests.post('https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?', data={'q': f'&stats.field=contigs_total_length_l&stats.field=contigs_count_l&stats.field=contigs_proteins_count_l&stats.field=contigs_min_length_l&stats.field=contigs_max_length_l&stats.field=scaffolds_count_l&stats.field=scaffolds_proteins_count_l&stats.field=scaffolds_total_length_l&stats.field=update_date_dt&stats.field=create_date_dt&indent=true&wt=xml&facet=true&facet.mincount=1&facet.limit={limit}&start=0&rows={rows}&sort=prefix_s%20asc&q=text%3A*{taxon}*%20AND%20project_s%3Awgs&stats=true'})
prefixes = extract_prefix_organism_pairs(response.text)
for prefix, organism in prefixes:
    print(f"{prefix}: {organism}")

[WGS index] Found 6 matching entries.
AWGM01: Diaphorina citri
JAKMOU01: Diaphorina citri
JAKMOV01: Diaphorina citri
JAKMOW01: Diaphorina citri
JBEUCC01: Cyamophila willieti
JBICBU01: Diaphorina citri

Not all prefixes are valid, let's check it with `filter_valid_wgs_prefixes`.

In [20]:
prefix_list = [p for p, _ in prefixes]
filter_valid_wgs_ids(prefix_list)

{'AWGM01': 'Diaphorina citri',
 'JAKMOU01': 'Diaphorina citri',
 'JAKMOV01': 'Diaphorina citri',
 'JAKMOW01': 'Diaphorina citri',
 'JBEUCC01': 'Cyamophila willieti',
 'JBICBU01': 'Diaphorina citri'}

Correct request to WGS database: $\color{red} WGS\_VDB://AAAA02$

```python
sequence = 'malakaketvasapvvvysksycpfcvrvkklfgqlgatfkaieldgesdgselqsalae'
data = {
    'CMD': 'Put',
    'PROGRAM': 'tblastn',
    'DATABASE': 'WGS_VDB://AAAA02',
    'QUERY': sequence,
}

df = run_blast(sequence, **data)
```

In [21]:
sequence = 'mpqmaplpwvflliltisvllymstilffslkpftsslsplhkkkfsikw'
dfs = run_blast(sequence, programm='tblastn', database='WGS_VDB://AEYK01')
dataframe = pd.DataFrame([{
    "description": df.subj_name,
    "score": df.score,
    "e_value": df.e_value,
    "identities": df.identities,
    "alignment_length": df.align_len,
    "query_alignment": df.query_align,
    "subject_alignment": df.sbjct_align,
    "subj_range": df.subj_range,
    "subject_length": df.subj_len,
    "accession": df.subj_id,
} for df in dfs])
display(dataframe.drop(columns=['query_alignment', 'subject_alignment']).head())
dataframe[['query_alignment', 'subject_alignment']].head()

NCBI initial response: 200
RID: 07Y121W7016 | Estimated wait: 6 sec
BLAST result link: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=07Y121W7016
Waiting for BLAST job to complete...

,description,score,e_value,identities,alignment_length,subj_range,subject_length,accession
0,"Vittaforma corneae ATCC 50505 cont1.88, whole ...",61,0.014,47,36,"(12806, 12901)",44660,AEYK01000088.1
1,"Vittaforma corneae ATCC 50505 cont1.140, whole...",47,1.3,34,35,"(2779, 2883)",3853,AEYK01000140.1
2,"Vittaforma corneae ATCC 50505 cont1.3, whole g...",45,2.8,31,36,"(24689, 24582)",26915,AEYK01000003.1
3,"Vittaforma corneae ATCC 50505 cont1.99, whole ...",45,2.9,39,44,"(12849, 12971)",28126,AEYK01000099.1
4,"Vittaforma corneae ATCC 50505 cont1.53, whole ...",44,3.6,62,13,"(16019, 16057)",25367,AEYK01000053.1

,query_alignment,subject_alignment
0,APLPWVFLLILTISVLLYMSTILFFSLKPFTSSLSP,APLPSTILLIRTIAAFLFNS----FALSPFSSACIP
1,LLILTISVLLYMSTI--LFFSLKPFTSSLSPLHKK,IFIRSIEVVKELGKLVHMFFSLKNRKKSINIVHKK
2,LTISVLLYMSTILFFSLKPFTSSLSPLHKKKFSIKW,LGVYLIISYSSVLFFRYSSTHNSYSCSSQ*KYSINW
3,APLPWVFLLILTISVLLYMSTILFFSLK-PFTSSLSPLHKKKFS,AELPWDLLLL*KFSENFCSK---FQALRMSFTSILREIHRKKQS
4,VLLYMSTILFFSL,VLLWLSTVVIFSL

In [4]:
taxons = ['Gregarinasina', 'Insecta', 'Crustacea', 'Annelida', 'Nematoda', 'Trematoda', 'Cestoda', 'jawless', 'fish']
prefixes = []
for taxon in taxons:
    print(taxon)
    response = requests.post(
        "https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?",
        data={'q': f'&wt=xml&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'}
        )
    prefixes.append(extract_prefix_organism_pairs(response.text))

Gregarinasina
Insecta
Crustacea
Annelida
Nematoda
Trematoda
Cestoda
jawless
fish

In [27]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [49]:
from main import wait_for_blast_results

In [50]:
len(wait_for_blast_results('079HGPWS013'))

100

In [43]:
wait_for_blast_results('079HGPWS013')

[self.subj_id='JF826404.1', self.subj_name='Amblyospora bogashovia isolate 1615 small subunit ribosomal RNA', self.subj_len=1358, self.subj_range=(146, 434), self.score='241', self.e_value='1e-120', self.identities=95, self.align_len=291, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGT-GATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGCAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTAGGTATATATG--GGATGTGTAAACAGCATTCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AF027684.1', self.subj_name='Edhazardia aedis small subunit ribosomal RNA gene, complete sequence', self.subj_len=1448, self.subj_range=(161, 449), self.score='241', self.e_value='1e-120', self.identities=94, self.align_len=290, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCTATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACGTTGAGGTAGTTACGAGGCGTAGTAT-TATGAAGTGTGTGTAAAGAGCATACTGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTTTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AY090055.1', self.subj_name='Amblyospora sp. isolate 1 small subunit ribosomal RNA gene, partial', self.subj_len=1348, self.subj_range=(164, 455), self.score='240', self.e_value='4e-120', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTCTTGTATGAAGCGTGTGTAAAAAGCATGCAGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826412.1', self.subj_name='Amblyospora mocrushinia isolate 1791 small subunit ribosomal', self.subj_len=1338, self.subj_range=(144, 435), self.score='240', self.e_value='4e-120', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTCCTGTATGAAGTGTGTGTAAAAAGCATGCTGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAATGTGCGTAGT',
 self.subj_id='AY013359.1', self.subj_name='Intrapredatorus barri 16S small subunit ribosomal RNA, partial', self.subj_len=1337, self.subj_range=(159, 449), self.score='239', self.e_value='1e-119', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGT--ATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACGGTGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTCCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGTGTCATTTATAGATGACAAGTGTGTAAACAGCATTTCAAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGC-GTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826408.1', self.subj_name='Amblyospora jurginia isolate 1689 small subunit ribosomal RNA', self.subj_len=1323, self.subj_range=(146, 434), self.score='238', self.e_value='5e-119', self.identities=94, self.align_len=291, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGG-GTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGTCGGTACGGTAAGGGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGCAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGT-ATTTGTAT-ATGGATTGTGTAAACAGCATTCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826413.1', self.subj_name='Amblyospora modestium isolate 1869 small subunit ribosomal RNA', self.subj_len=1304, self.subj_range=(141, 428), self.score='238', self.e_value='5e-119', self.identities=94, self.align_len=291, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTA-AAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACGGTGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGACGGCTCCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTCACGAGGTGTCAGA-G-ATGACCGGTGTGTAAACAGCAT-CGAGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AY090051.1', self.subj_name='Amblyospora indicola isolate 1 small subunit ribosomal RNA gene,', self.subj_len=1305, self.subj_range=(144, 431), self.score='238', self.e_value='5e-119', self.identities=94, self.align_len=290, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACGGTGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGACGGCTCCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTCAT-TG-ATGAACAGTGTGCAAACAGCATTGTAAAGTATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AY090052.1', self.subj_name='Amblyospora opacita isolate 1 small subunit ribosomal RNA gene,', self.subj_len=1371, self.subj_range=(145, 433), self.score='238', self.e_value='5e-119', self.identities=94, self.align_len=290, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTTAT-TGTATGAACTGTGCGTTTAAAGCATAGTGAAGTACTGGAGGGCAAGCCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGCAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AY090048.1', self.subj_name='Amblyospora weiseri isolate 1 small subunit ribosomal RNA gene,', self.subj_len=1333, self.subj_range=(145, 433), self.score='238', self.e_value='5e-119', self.identities=94, self.align_len=291, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGG-GTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGTCGGTACGGTAAGGGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGCAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGT-ATTTGTAT-ATGGATTGTGTAAACAGCATTCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826402.1', self.subj_name='Amblyospora bakcharia isolate 1686 small subunit ribosomal RNA', self.subj_len=1332, self.subj_range=(144, 435), self.score='237', self.e_value='2e-118', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTCTTGTATGAAGCATGTGTAAAAAGCATGCAGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='HM594266.1', self.subj_name='Amblyospora rugosa isolate 3 small subunit ribosomal RNA gene,', self.subj_len=1376, self.subj_range=(162, 453), self.score='237', self.e_value='2e-118', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTTTTGTATGAAGTGTGTGTAAAAAGCATGCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAATGTGCGTAGT',
 self.subj_id='HM594264.1', self.subj_name='Amblyospora rugosa isolate 1 small subunit ribosomal RNA gene,', self.subj_len=1456, self.subj_range=(162, 453), self.score='237', self.e_value='2e-118', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTTTTGTATGAAGTGTGTGTAAAAAGCATGCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAATGTGCGTAGT',
 self.subj_id='JF826414.1', self.subj_name='Amblyospora rugosa isolate 1617 small subunit ribosomal RNA gene,', self.subj_len=1339, self.subj_range=(144, 435), self.score='237', self.e_value='2e-118', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTTTTGTATGAAGTGTGTGTAAAAAGCATGCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAATGTGCGTAGT',
 self.subj_id='HM594265.1', self.subj_name='Amblyospora rugosa isolate 2 small subunit ribosomal RNA gene,', self.subj_len=1347, self.subj_range=(146, 437), self.score='237', self.e_value='2e-118', self.identities=94, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATA--TGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTTTTGTATGAAGTGTGTGTAAAAAGCATGCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAATGTGCGTAGT',
 self.subj_id='JF826418.1', self.subj_name='Amblyospora timirasia isolate 1687 small subunit ribosomal RNA', self.subj_len=1420, self.subj_range=(146, 433), self.score='232', self.e_value='1e-115', self.identities=93, self.align_len=290, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCTATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTAAT-T-TATGTAGTATGTATAAATGACATACTGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826405.1', self.subj_name='Amblyospora chulymia isolate 1640 small subunit ribosomal RNA', self.subj_len=1342, self.subj_range=(144, 432), self.score='232', self.e_value='1e-115', self.identities=93, self.align_len=290, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTAGGAT-TATGAAGCATGTATAAAGAGCATGCCGAAGTATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AY326270.1', self.subj_name='Amblyospora salinaria 16S ribosomal RNA gene, partial sequence', self.subj_len=1508, self.subj_range=(290, 581), self.score='231', self.e_value='4e-115', self.identities=93, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATG-TATGACGGGTGTGTAAAAAGCATACTAAAG-CACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTAGTCGGTACGGTAAAGGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGTGTGACATTCTATGAACCGTGTCTTAAAAGCAGGGTTAAGACATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='AY090053.1', self.subj_name='Amblyospora sp. isolate 1 small subunit ribosomal RNA gene, partial', self.subj_len=1352, self.subj_range=(153, 444), self.score='231', self.e_value='4e-115', self.identities=93, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATG-TATGACGGGTGTGTAAAAAGCATACTAAAG-CACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTAGTCGGTACGGTAAAGGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGTGTGACATTCTATGAACCGTGTCTTAAAAGCAGGGTTAAGACATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826409.1', self.subj_name='Amblyospora kazankia isolate 1507 small subunit ribosomal RNA', self.subj_len=1338, self.subj_range=(144, 435), self.score='231', self.e_value='4e-115', self.identities=93, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATAT--GTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCTATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACTTTAAGTATGAGTTTTGTGTAAAAAGCATGATGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826407.1', self.subj_name='Amblyospora hristinia isolate 1678 small subunit ribosomal RNA', self.subj_len=1289, self.subj_range=(148, 437), self.score='230', self.e_value='1e-114', self.identities=93, self.align_len=292, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGT-G-ATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTAGCAT-T-TATGTGGTATGTGTAAACAGCATATCGAAGTATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAATAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',
 self.subj_id='JF826411.1', self.subj_name='Amblyospora mavlukevia isolate 1676 small subunit ribosomal RNA', self.subj_len=1355, self.subj_range=(144, 432), self.score='229', self.e_value='5e-114', self.identities=93, self.align_len=290, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGGTGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGACGGTACGGTAAGTGCGTACCGAGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGGGGCGTACT-TGTATGCAGCATGTGTAAACTCCATGCCGAAGTACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAATGTGCGTAGT',
 self.subj_id='AY090061.1', self.subj_name='Amblyospora criniferis isolate 1 small subunit ribosomal RNA', self.subj_len=1291, self.subj_range=(145, 433), self.score='229', self.e_value='5e-114', self.identities=93, self.align_len=291, self.query_align='TGACCTATCAGCTTGTCGGTACGGTAAGTGCGTACGGAGGCGATGACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTACCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGTGATATGTATGACGGG-TGTGTAAAAAGCATACTAAAGCACTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAGTAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT', self.sbjct_align='TGACCTATCAGCTTGTCGGTACGATAAGTGCGTACCGTGGCGATAACGGGTAACGGGGAATATGGGTTTTATTCCGGAGAGGGAGCCTGAGAGATGGCTGCCACGTCCAAGGACGGCAGCAGGCGCGAAACTTACCCAATGAACATTGAGGTAGTTACGAGGCGT-ATTTATAT-ACGGGATGTATAAATAGCATTCCCAAGTATTGGAGGGCAAGCCTGGTGCCAGCAGCCGCGGTAATACCAGCTCCAATAGCGTCTGTGTTTATTGCTGCGGTTAAAACGTGCGTAGT',

In [88]:
rid = '079HGPWS013'
result = requests.get(
    "https://blast.ncbi.nlm.nih.gov/Blast.cgi",
    params={
        "CMD": "Get",
        "FORMAT_OBJECT": "Alignment",
        "FORMAT_TYPE": "Text",
        "RID": rid,
        "DESCRIPTIONS": 100,
        "ALIGNMENTS": 100,
    },
)
with open("./tests/data/blast_output.txt", "w", encoding="utf-8") as f:
    f.write(result.text)

In [84]:
from main import parse_blast_text_output

In [104]:
result.text
with open("./tests/data/blast_output.txt", "w", encoding="utf-8") as f:
    f.write(result.text)

In [112]:
response = requests.post(
            "https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?",
            data={'q': f'&wt=xml&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'})

results = extract_prefix_organism_pairs(response.text)
with open("tests/data/expected_prefixes.txt", "w", encoding="utf-8") as f:
    f.write(results)

TypeError: write() argument must be str, not list

In [119]:
prefix_list = [p for p, _ in results]
filter_valid_wgs_ids(prefix_list)

{'ABJQ01': 'Ascogregarina taiwanensis',
 'AFNH02': 'Gregarina niphandrodes',
 'JAHYSE01': 'Porospora cf. gigantea A',
 'JAHYSF01': 'Porospora cf. gigantea B',
 'JAQIFP01': 'Ophryocystis elektroscirrha',
 'JBLWGC01': 'Leidyana gryllorum'}

In [120]:
prefix_list = ["ABJQ01", "AFNH01", "AFNH02", "JAHYSE01", "JAHYSF01", "JAQIFP01", "JBLWGC01"]
filter_valid_wgs_ids(prefix_list)

{'ABJQ01': 'Ascogregarina taiwanensis',
 'AFNH02': 'Gregarina niphandrodes',
 'JAHYSE01': 'Porospora cf. gigantea A',
 'JAHYSF01': 'Porospora cf. gigantea B',
 'JAQIFP01': 'Ophryocystis elektroscirrha',
 'JBLWGC01': 'Leidyana gryllorum'}

In [123]:
with open("tests/data/db_species_table.html", "w", encoding="utf-8") as f:
    f.write(response.text)  # где `response` — это результат requests.get(...) внутри `filter_valid_wgs_ids`

In [ ]:
taxon = 'Gregarina'

response = requests.post(
            "https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?",
            data={'q': f'&wt=xml&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'})
prefixes = extract_prefix_organism_pairs(response.text)

with open("tests/data/db_species_table.html", "w", encoding="utf-8") as f:
    f.write(response.text)

response.text

'<?xml version="1.0" encoding="UTF-8"?>\n<response>\n\n<lst name="responseHeader">\n  <bool name="zkConnected">true</bool>\n  <int name="status">0</int>\n  <int name="QTime">1188</int>\n  <lst name="params">\n    <str name="q">(text:*Gregarina* AND project_s:wgs) AND ( state_s:live OR state_s:suppressed OR state_s:dead OR state_s:replaced OR state_s:unverified )</str>\n    <str name="trusted">0</str>\n    <str name="wt">xml</str>\n  </lst>\n</lst>\n<result name="response" numFound="7" start="0" numFoundExact="true">\n  <doc>\n    <str name="id">AFNH01</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">AFNH01</str>\n    <long name="version_l">1</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">replaced</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA59799</str>\n    <date name="update_date_dt">2011-06-27T00:00:00Z</date>\n    <date name="create_date_dt">2011-06-27T00:00:00Z</date>\n    <date name="last_update_dt">2018-05-01T16:32:00Z</date>\n    <str name="seqid_s">AFNH00000000</str>\n    <str name="gi_s">338246341</str>\n    <long name="taxid_l">110365</long>\n    <str name="organism_an">Gregarina niphandrodes</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>35087</long>\n      <long>35088</long>\n      <long>35089</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Eugregarinorida</str>\n      <str>Gregarinidae</str>\n      <str>Gregarina</str>\n    </arr>\n    <str name="lineages_s">,2759,33630,5794,1280412,35086,35087,35088,35089,110365,</str>\n    <arr name="keyword_ss">\n      <str>WGS</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n    </arr>\n    <long name="contigs_count_l">3680</long>\n    <long name="contigs_proteins_count_l">0</long>\n    <long name="contigs_min_length_l">93</long>\n    <long name="contigs_max_length_l">77023</long>\n    <long name="contigs_total_length_l">15362869</long>\n    <str name="contigs_annotated_s">No</str>\n    <long name="scaffolds_count_l">0</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">0</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <str name="dev_stage_s">cysts</str>\n    <str name="host_s">Tenebrio molitor</str>\n    <str name="isolation_source_s">wild beetles</str>\n    <arr name="other_src_ss">\n      <str>dev_stage: cysts</str>\n      <str>host: Tenebrio molitor</str>\n      <str>isolation_source: wild beetles</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1807585034146676741</long></doc>\n  <doc>\n    <str name="id">ABJQ01</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">ABJQ01</str>\n    <long name="version_l">1</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">live</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA27765</str>\n    <date name="update_date_dt">2014-08-06T00:00:00Z</date>\n    <date name="create_date_dt">2010-01-28T00:00:00Z</date>\n    <date name="last_update_dt">2017-11-18T15:21:00Z</date>\n    <str name="seqid_s">ABJQ00000000</str>\n    <str name="gi_s">284819907</str>\n    <long name="taxid_l">158379</long>\n    <str name="organism_an">Ascogregarina taiwanensis</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>35087</long>\n      <long>158377</long>\n      <long>158378</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Eugregarinorida</str>\n      <str>Lecudinidae</str>\n      <str>Ascogregarina</str>\n    </arr>\n    <str name="lineages_s">,2759,33630,5794,1280412,35086,35087,158377,158378,158379,</str>\n    <arr name="biosample_ss">\n      <str>SAMN02953717</str>\n    </arr>\n    <arr name="keyword_ss">\n      <str>WGS</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n    </arr>\n    <long name="contigs_count_l">5379</long>\n    <long name="contigs_proteins_count_l">0</long>\n    <long name="contigs_min_length_l">200</long>\n    <long name="contigs_max_length_l">11727</long>\n    <long name="contigs_total_length_l">6149411</long>\n    <str name="contigs_annotated_s">Yes</str>\n    <long name="scaffolds_count_l">0</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">0</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <str name="dev_stage_s">oocyst</str>\n    <str name="host_s">Aedes albopictus</str>\n    <str name="isolate_s">Tauyuan-1</str>\n    <str name="isolation_source_s">larvae of Aedes albopictus (Asian tiger mosquito)</str>\n    <arr name="other_src_ss">\n      <str>dev_stage: oocyst</str>\n      <str>host: Aedes albopictus</str>\n      <str>isolation_source: larvae of Aedes albopictus (Asian tiger mosquito)</str>\n    </arr>\n    <arr name="infra_name_ss">\n      <str>isolate: Tauyuan-1</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1807585026597978122</long></doc>\n  <doc>\n    <str name="id">AFNH02</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">AFNH02</str>\n    <long name="version_l">2</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">live</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA59799</str>\n    <date name="update_date_dt">2022-03-15T00:00:00Z</date>\n    <date name="create_date_dt">2012-03-29T00:00:00Z</date>\n    <date name="last_update_dt">2022-03-15T13:57:06.843Z</date>\n    <str name="seqid_s">AFNH00000000</str>\n    <str name="gi_s">381423459</str>\n    <long name="taxid_l">110365</long>\n    <str name="organism_an">Gregarina niphandrodes</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>2698737</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>35087</long>\n      <long>35088</long>\n      <long>35089</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Sar</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Eugregarinorida</str>\n      <str>Gregarinidae</str>\n      <str>Gregarina</str>\n    </arr>\n    <str name="lineages_s">,2759,2698737,33630,5794,1280412,35086,35087,35088,35089,110365,</str>\n    <arr name="biosample_ss">\n      <str>SAMN01120375</str>\n    </arr>\n    <arr name="keyword_ss">\n      <str>WGS</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n    </arr>\n    <long name="contigs_count_l">2679</long>\n    <long name="contigs_proteins_count_l">6375</long>\n    <long name="contigs_min_length_l">211</long>\n    <long name="contigs_max_length_l">95602</long>\n    <long name="contigs_total_length_l">13637929</long>\n    <str name="contigs_annotated_s">Yes</str>\n    <long name="scaffolds_count_l">469</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">14009070</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <arr name="scaffolds_range_ss">\n      <str>KK211454-KK211922</str>\n    </arr>\n    <str name="dev_stage_s">cysts</str>\n    <str name="host_s">Tenebrio molitor</str>\n    <str name="isolation_source_s">wild beetles</str>\n    <arr name="other_src_ss">\n      <str>dev_stage: cysts</str>\n      <str>host: Tenebrio molitor</str>\n      <str>isolation_source: wild beetles</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1807586578263965698</long></doc>\n  <doc>\n    <str name="id">JAHYSE01</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">JAHYSE01</str>\n    <long name="version_l">1</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">live</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA734792</str>\n    <date name="update_date_dt">2022-07-11T00:00:00Z</date>\n    <date name="create_date_dt">2021-09-14T00:00:00Z</date>\n    <date name="last_update_dt">2024-07-31T19:39:25.450Z</date>\n    <str name="seqid_s">JAHYSE000000000</str>\n    <str name="gi_s">2094642169</str>\n    <long name="taxid_l">2853593</long>\n    <str name="organism_an">Porospora cf. gigantea A</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>2698737</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>35087</long>\n      <long>947094</long>\n      <long>947096</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Sar</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Eugregarinorida</str>\n      <str>Porosporidae</str>\n      <str>Porospora</str>\n    </arr>\n    <str name="lineages_s">,2759,2698737,33630,5794,1280412,35086,35087,947094,947096,2853593,</str>\n    <arr name="biosample_ss">\n      <str>SAMN19872688</str>\n    </arr>\n    <arr name="keyword_ss">\n      <str>WGS; MAG</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n      <str>MAG</str>\n    </arr>\n    <long name="contigs_count_l">787</long>\n    <long name="contigs_proteins_count_l">8895</long>\n    <long name="contigs_min_length_l">1000</long>\n    <long name="contigs_max_length_l">148957</long>\n    <long name="contigs_total_length_l">8812657</long>\n    <str name="contigs_annotated_s">Yes</str>\n    <long name="scaffolds_count_l">0</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">0</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <str name="host_s">Homarus gammarus</str>\n    <str name="isolate_s">A</str>\n    <str name="isolation_source_s">Roscoff Lobster tank and facility Roscoff bay</str>\n    <str name="metagenome_source_s">symbiont metagenome</str>\n    <arr name="other_src_ss">\n      <str>host: Homarus gammarus</str>\n      <str>isolation_source: Roscoff Lobster tank and facility Roscoff bay</str>\n      <str>metagenome_source: symbiont metagenome</str>\n    </arr>\n    <arr name="infra_name_ss">\n      <str>isolate: A</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1807588742135808001</long></doc>\n  <doc>\n    <str name="id">JAQIFP01</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">JAQIFP01</str>\n    <long name="version_l">1</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">live</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA906508</str>\n    <date name="update_date_dt">2023-05-31T00:00:00Z</date>\n    <date name="create_date_dt">2023-05-31T00:00:00Z</date>\n    <date name="last_update_dt">2023-05-31T10:55:39.763Z</date>\n    <str name="seqid_s">JAQIFP000000000</str>\n    <str name="gi_s">2512353238</str>\n    <long name="taxid_l">110372</long>\n    <str name="organism_an">Ophryocystis elektroscirrha</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>2698737</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>238088</long>\n      <long>110370</long>\n      <long>110371</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Sar</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Neogregarinorida</str>\n      <str>Ophryocystidae</str>\n      <str>Ophryocystis</str>\n    </arr>\n    <str name="lineages_s">,2759,2698737,33630,5794,1280412,35086,238088,110370,110371,110372,</str>\n    <arr name="biosample_ss">\n      <str>SAMN31926794</str>\n    </arr>\n    <arr name="keyword_ss">\n      <str>WGS</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n    </arr>\n    <long name="contigs_count_l">155</long>\n    <long name="contigs_proteins_count_l">0</long>\n    <long name="contigs_min_length_l">2781</long>\n    <long name="contigs_max_length_l">423541</long>\n    <long name="contigs_total_length_l">8598435</long>\n    <str name="contigs_annotated_s">No</str>\n    <long name="scaffolds_count_l">0</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">0</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <str name="host_s">Danaus plexippus</str>\n    <str name="isolate_s">DRL_2022a</str>\n    <str name="isolation_source_s">whole body</str>\n    <arr name="other_src_ss">\n      <str>host: Danaus plexippus</str>\n      <str>isolation_source: whole body</str>\n    </arr>\n    <arr name="infra_name_ss">\n      <str>isolate: DRL_2022a</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1807587028265598979</long></doc>\n  <doc>\n    <str name="id">JAHYSF01</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">JAHYSF01</str>\n    <long name="version_l">1</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">live</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA734792</str>\n    <date name="update_date_dt">2024-08-16T00:00:00Z</date>\n    <date name="create_date_dt">2021-09-14T00:00:00Z</date>\n    <date name="last_update_dt">2024-08-16T16:51:10.467Z</date>\n    <str name="seqid_s">JAHYSF000000000</str>\n    <str name="gi_s">2094643179</str>\n    <long name="taxid_l">2853592</long>\n    <str name="organism_an">Porospora cf. gigantea B</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>2698737</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>35087</long>\n      <long>947094</long>\n      <long>947096</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Sar</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Eugregarinorida</str>\n      <str>Porosporidae</str>\n      <str>Porospora</str>\n    </arr>\n    <str name="lineages_s">,2759,2698737,33630,5794,1280412,35086,35087,947094,947096,2853592,</str>\n    <arr name="biosample_ss">\n      <str>SAMN19872687</str>\n    </arr>\n    <arr name="keyword_ss">\n      <str>WGS; MAG</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n      <str>MAG</str>\n    </arr>\n    <long name="contigs_count_l">918</long>\n    <long name="contigs_proteins_count_l">9003</long>\n    <long name="contigs_min_length_l">992</long>\n    <long name="contigs_max_length_l">148095</long>\n    <long name="contigs_total_length_l">9054784</long>\n    <str name="contigs_annotated_s">Yes</str>\n    <long name="scaffolds_count_l">0</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">0</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <str name="host_s">Homarus gammarus</str>\n    <str name="isolate_s">B</str>\n    <str name="isolation_source_s">Roscoff Lobster tank and facility Roscoff bay</str>\n    <str name="metagenome_source_s">symbiont metagenome</str>\n    <arr name="other_src_ss">\n      <str>host: Homarus gammarus</str>\n      <str>isolation_source: Roscoff Lobster tank and facility Roscoff bay</str>\n      <str>metagenome_source: symbiont metagenome</str>\n    </arr>\n    <arr name="infra_name_ss">\n      <str>isolate: B</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1807588757155610625</long></doc>\n  <doc>\n    <str name="id">JBLWGC01</str>\n    <str name="project_s">WGS</str>\n    <str name="prefix_s">JBLWGC01</str>\n    <long name="version_l">1</long>\n    <str name="div_s">INV</str>\n    <str name="state_s">live</str>\n    <str name="vdb_only_s">No</str>\n    <str name="src_db_s">GenBank</str>\n    <str name="bioproject_s">PRJNA1225920</str>\n    <date name="update_date_dt">2025-03-21T00:00:00Z</date>\n    <date name="create_date_dt">2025-03-21T00:00:00Z</date>\n    <date name="last_update_dt">2025-03-21T14:53:55.267Z</date>\n    <str name="seqid_s">JBLWGC000000000</str>\n    <str name="gi_s">2937393332</str>\n    <long name="taxid_l">3401061</long>\n    <str name="organism_an">Leidyana gryllorum</str>\n    <arr name="lineage_taxid_ls">\n      <long>2759</long>\n      <long>2698737</long>\n      <long>33630</long>\n      <long>5794</long>\n      <long>1280412</long>\n      <long>35086</long>\n      <long>35087</long>\n      <long>196591</long>\n      <long>196592</long>\n    </arr>\n    <arr name="lineage_name_ss">\n      <str>Eukaryota</str>\n      <str>Sar</str>\n      <str>Alveolata</str>\n      <str>Apicomplexa</str>\n      <str>Conoidasida</str>\n      <str>Gregarinasina</str>\n      <str>Eugregarinorida</str>\n      <str>Leidyanidae</str>\n      <str>Leidyana</str>\n    </arr>\n    <str name="lineages_s">,2759,2698737,33630,5794,1280412,35086,35087,196591,196592,3401061,</str>\n    <arr name="biosample_ss">\n      <str>SAMN46910021</str>\n    </arr>\n    <arr name="keyword_ss">\n      <str>WGS</str>\n    </arr>\n    <arr name="keyword_part_ss">\n      <str>WGS</str>\n    </arr>\n    <long name="contigs_count_l">237</long>\n    <long name="contigs_proteins_count_l">0</long>\n    <long name="contigs_min_length_l">506</long>\n    <long name="contigs_max_length_l">1726050</long>\n    <long name="contigs_total_length_l">15504140</long>\n    <str name="contigs_annotated_s">No</str>\n    <long name="scaffolds_count_l">0</long>\n    <long name="scaffolds_proteins_count_l">0</long>\n    <long name="scaffolds_total_length_l">0</long>\n    <str name="scaffolds_annotated_s">No</str>\n    <str name="host_s">Acheta domesticus</str>\n    <str name="isolation_source_s">feces</str>\n    <str name="strain_s">EB-2025a</str>\n    <arr name="other_src_ss">\n      <str>host: Acheta domesticus</str>\n      <str>isolation_source: feces</str>\n    </arr>\n    <arr name="infra_name_ss">\n      <str>strain: EB-2025a</str>\n    </arr>\n    <str name="cluster_s"/>\n    <str name="gap_study_s"/>\n    <str name="consent_group_s"/>\n    <str name="targeted_locus_name_s"/>\n    <long name="_version_">1827233859007152129</long></doc>\n</result>\n</response>\n'

In [ ]:
prefixes

In [130]:
with open("tests/data/expected_prefixes.txt", "w", encoding="utf-8") as f:
    for prefix, organism in prefixes:
        f.write(f"{prefix}\t{organism}\n")

In [138]:
results = [
    ('AFNH01', 'Gregarina niphandrodes'),
    ('ABJQ01', 'Ascogregarina taiwanensis'),
    ('JAHYSE01', 'Porospora cf. gigantea A'),
    ('JAQIFP01', 'Ophryocystis elektroscirrha'),
    ('AFNH02', 'Gregarina niphandrodes'),
    ('JAHYSF01', 'Porospora cf. gigantea B'),
    ('JBLWGC01', 'Leidyana gryllorum'),
]

with open("tests/data/expected_prefixes.txt", "w", encoding="utf-8") as f:
    for prefix, organism in results:
        f.write(f"{prefix}\t{organism}\n")

In [103]:
headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/134.0.0.0 Safari/537.36"),
        "Referer": "https://blast.ncbi.nlm.nih.gov/Blast.cgi",
        "Origin": "https://blast.ncbi.nlm.nih.gov",
        "Accept": "*/*",
    }
db_string = ",".join(f"WGS_VDB://{p}" for p in prefixes)
params = {"DATABASE": db_string, "CMD": "getDBOrg"}

response = requests.get(
        "https://blast.ncbi.nlm.nih.gov/getDBInfo.cgi", headers=headers, params=params
    )

with open("./tests/data/db_species_table.html", "w", encoding="utf-8") as f:
    f.write(response.text)

In [98]:
r = parse_blast_text_output(result.text)
with open("./tests/data/parse_output.txt", "w", encoding="utf-8") as f:
    f.write(str(r[0]))

import pickle

r = parse_blast_text_output(result.text)
with open("tests/data/parse_output.pkl", "wb") as f:
    pickle.dump(r, f)

In [132]:
taxon = 'gregarina'
response = requests.post(
            "https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?",
            data={'q': f'&wt=xml&q=text%3A*{taxon}*%20AND%20project_s%3Awgs'})

extract_prefix_organism_pairs(response.text)

with open("./tests/data/prefixes_response.xml", "w", encoding="utf-8") as f:
    f.write(response.text)

In [136]:
prefix_list = ["ABJQ01", "AFNH01", "AFNH02", "JAHYSE01", "JAHYSF01", "JAQIFP01", "JBLWGC01"]
result = filter_valid_wgs_ids(prefix_list)

print(result)

{'ABJQ01': 'Ascogregarina taiwanensis', 'AFNH02': 'Gregarina niphandrodes', 'JAHYSE01': 'Porospora cf. gigantea A', 'JAHYSF01': 'Porospora cf. gigantea B', 'JAQIFP01': 'Ophryocystis elektroscirrha', 'JBLWGC01': 'Leidyana gryllorum'}

In [137]:
import json

# Это твой текущий список префиксов
prefix_list = ["ABJQ01", "AFNH01", "AFNH02", "JAHYSE01", "JAHYSF01", "JAQIFP01", "JBLWGC01"]

from main import filter_valid_wgs_ids  # Импортируй откуда надо
result = filter_valid_wgs_ids(prefix_list)

# ===== Сохраняем HTML =====
html = """
<html>
  <body>
    <table id="dbSpecies">
      <tr><th>Database</th><th>Organism</th></tr>
"""
for prefix, organism in result.items():
    html += f"<tr><td>WGS_VDB://{prefix}</td><td>{organism}</td></tr>\n"

html += """
    </table>
  </body>
</html>
"""

with open("tests/data/db_species_table.html", "w", encoding="utf-8") as f:
    f.write(html)

# ===== Сохраняем JSON =====
with open("tests/data/expected_filtered_prefixes.json", "w", encoding="utf-8") as f:
    json.dump(result, f, indent=2)

print("✅ Test files generated successfully.")

✅ Test files generated successfully.

In [58]:
res = extract_prefix_organism_pairs(response)

with open("./tests/data/expected_prefixes.txt", "w", encoding="utf-8") as f:
    f.write(res)

TypeError: a bytes-like object is required, not 'Response'

In [59]:
limit = 1000
rows = 1000
taxon = 'gregarina'
response = requests.post('https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?', data={'q': f'&stats.field=contigs_total_length_l&stats.field=contigs_count_l&stats.field=contigs_proteins_count_l&stats.field=contigs_min_length_l&stats.field=contigs_max_length_l&stats.field=scaffolds_count_l&stats.field=scaffolds_proteins_count_l&stats.field=scaffolds_total_length_l&stats.field=update_date_dt&stats.field=create_date_dt&indent=true&wt=xml&facet=true&facet.mincount=1&facet.limit={limit}&start=0&rows={rows}&sort=prefix_s%20asc&q=text%3A*{taxon}*%20AND%20project_s%3Awgs&stats=true'})
prefixes = extract_prefix_organism_pairs(response.text)
for prefix, organism in prefixes:
    print(f"{prefix}: {organism}")

[WGS index] Found 7 matching entries.
ABJQ01: Ascogregarina taiwanensis
AFNH01: Gregarina niphandrodes
AFNH02: Gregarina niphandrodes
JAHYSE01: Porospora cf. gigantea A
JAHYSF01: Porospora cf. gigantea B
JAQIFP01: Ophryocystis elektroscirrha
JBLWGC01: Leidyana gryllorum

In [76]:
prefixes = requests.post('https://www.ncbi.nlm.nih.gov/Traces/wgs/index.cgi?', data={'q': f'&stats.field=contigs_total_length_l&stats.field=contigs_count_l&stats.field=contigs_proteins_count_l&stats.field=contigs_min_length_l&stats.field=contigs_max_length_l&stats.field=scaffolds_count_l&stats.field=scaffolds_proteins_count_l&stats.field=scaffolds_total_length_l&stats.field=update_date_dt&stats.field=create_date_dt&indent=true&wt=xml&facet=true&facet.mincount=1&facet.limit={limit}&start=0&rows={rows}&sort=prefix_s%20asc&q=text%3A*{taxon}*%20AND%20project_s%3Awgs&stats=true'})
prefixes = extract_prefix_organism_pairs(prefixes.text)
prefix_list = [p for p, _ in prefixes]
with open("./tests/data/prefix_list.txt", "w", encoding="utf-8") as f:
    f.write("], [".join(prefix_list))

[WGS index] Found 7 matching entries.

In [75]:
prefix_list

['ABJQ01', 'AFNH01', 'AFNH02', 'JAHYSE01', 'JAHYSF01', 'JAQIFP01', 'JBLWGC01']

In [78]:
prefix_list = [p for p, _ in prefixes]
valid = filter_valid_wgs_ids(prefix_list)
print(prefixes)
print(len(valid))
print(valid)

[('ABJQ01', 'Ascogregarina taiwanensis'), ('AFNH01', 'Gregarina niphandrodes'), ('AFNH02', 'Gregarina niphandrodes'), ('JAHYSE01', 'Porospora cf. gigantea A'), ('JAHYSF01', 'Porospora cf. gigantea B'), ('JAQIFP01', 'Ophryocystis elektroscirrha'), ('JBLWGC01', 'Leidyana gryllorum')]
6
{'ABJQ01': 'Ascogregarina taiwanensis', 'AFNH02': 'Gregarina niphandrodes', 'JAHYSE01': 'Porospora cf. gigantea A', 'JAHYSF01': 'Porospora cf. gigantea B', 'JAQIFP01': 'Ophryocystis elektroscirrha', 'JBLWGC01': 'Leidyana gryllorum'}

In [79]:
valid

{'ABJQ01': 'Ascogregarina taiwanensis',
 'AFNH02': 'Gregarina niphandrodes',
 'JAHYSE01': 'Porospora cf. gigantea A',
 'JAHYSF01': 'Porospora cf. gigantea B',
 'JAQIFP01': 'Ophryocystis elektroscirrha',
 'JBLWGC01': 'Leidyana gryllorum'}

In [71]:
prefix_list

['ABJQ01', 'AFNH01', 'AFNH02', 'JAHYSE01', 'JAHYSF01', 'JAQIFP01', 'JBLWGC01']